### ISSUE TITLE
Fails capturing on java project with JBasics.Class_structure_error Illegal method index (does not refer to a constant method)

### ISSUE THREAD

**Issue by AndreasVoellmy** [facebook/infer#1019]
Infer fails to analyze one of my projects. There are lots of errors like this:

`create_icfg raised JBasics.Class_structure_error Illegal method index (does not refer to a constant method) on ...`

And then finally, I see this: 
```
Uncaught Internal Error: (Invalid_argument "index out of bounds")
Error backtrace:
Raised by primitive operation at file "bir.ml", line 2485, characters 18-43
Called from file "array.ml", line 124, characters 31-51
Called from file "bir.ml", line 2480, characters 4-485
Called from file "bir.ml", line 2834, characters 23-47
Called from file "bir.ml", line 2882, characters 29-54
Called from file "jBir.ml" (inlined), line 43, characters 12-51
Called from file "java/jTrans.ml" (inlined), line 271, characters 2-85
Called from file "java/jTrans.ml", line 409, characters 20-55
Called from file "java/jFrontend.ml", line 93, characters 10-84
Called from file "java/jFrontend.ml", line 158, characters 12-72
Called from file "ptmap.ml", line 165, characters 26-35
Called from file "ptmap.ml", line 165, characters 26-35
Called from file "ptmap.ml", line 165, characters 26-35
Called from file "java/jFrontend.ml", line 195, characters 26-43
Called from file "ptmap.ml", line 165, characters 26-35
Called from file "ptmap.ml", line 165, characters 26-35
Called from file "ptmap.ml", line 165, characters 26-35
Called from file "ptmap.ml", line 165, characters 26-35
Called from file "ptmap.ml", line 165, characters 26-35
Called from file "ptmap.ml", line 165, characters 26-35
Called from file "ptmap.ml", line 165, characters 26-35
Called from file "ptmap.ml", line 165, characters 26-35
Called from file "ptmap.ml", line 165, characters 26-35
Called from file "java/jFrontend.ml", line 198, characters 4-201
Called from file "java/jMain.ml" (inlined), line 34, characters 4-111
Called from file "java/jMain.ml" (inlined), line 100, characters 6-85
Called from file "java/jMain.ml", line 106, characters 10-72
Called from file "src/map.ml", line 637, characters 29-39
Called from file "src/map.ml", line 637, characters 29-39
Called from file "src/map.ml", line 637, characters 29-39
Called from file "src/map.ml", line 637, characters 29-39
Called from file "src/map.ml", line 637, characters 29-39
Called from file "src/map.ml" (inlined), line 637, characters 29-39
Called from file "src/map.ml" (inlined), line 1282, characters 19-40
Called from file "java/jMain.ml", line 102, characters 2-446
Called from file "java/jMain.ml" (inlined), line 147, characters 40-79
Called from file "integration/Javac.ml", line 88, characters 48-87
Called from file "infer.ml", line 20, characters 2-36
Called from file "infer.ml", line 130, characters 8-54
```

This is running `Infer version v0.15.0` on OS X.

**Comment by martintrojer** [comment]
Hello,

is it possible to provide a bit more information so we can try to reproduce this error?

What command you run, sample input that causes the crash would also help.

**Comment by jvillard** [comment]
Which version of infer are you using?

**Comment by AndreasVoellmy** [comment]
`Infer version v0.15.0`

**Comment by JervenBolleman** [comment]
I see a very similar issue, might it be because I compiled with javac from openjdk-11?

**Comment by jvillard** [comment]
@JervenBolleman yes that could explain why the library we use to parse Java bytecode crashes.

@AndreasVoellmy if you have a repro you can report it on [Sawja's bugtracker](https://gforge.inria.fr/tracker/?atid=2815&group_id=686&func=browse).

**Comment by hmusavi** [comment]
I'm having the same issue while running infer capture in a Centos container. Lots of messages indicating:
```
create_icfg raised JBasics.Class_structure_error Illegal method index
```

followed eventually by:
```
create_icfg raised JBasics.Class_structure_error Illegal method index (does not refer to a constant method) on List ...
Traceback (most recent call last):
Running and capturing gradle compilation...
Failed to execute: /opt/infer-linux64-v0.16.0/lib/infer/infer/lib/python/inferlib/../../../bin/infer capture --continue -- javac -d ...

/root/.gradle/  File "/opt/infer-linux64-v0.16.0/lib/infer/infer/bin/../lib/python/infer.py", line 203, in <module>
-XDuseUnsharedTable=true @/root/apps/infer-out/filelists/gradle_adCBT4.txt
    main()
  File "/opt/infer-linux64-v0.16.0/lib/infer/infer/bin/../lib/python/infer.py", line 185, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/opt/infer-linux64-v0.16.0/lib/infer/infer/lib/python/inferlib/capture/gradle.py", line 214, in capture
    capture_code = util.run_compilation_commands(cmds)
  File "/opt/infer-linux64-v0.16.0/lib/infer/infer/lib/python/inferlib/capture/util.py", line 46, in run_compilation_commands
    if cmd.start() != os.EX_OK:
  File "/opt/infer-linux64-v0.16.0/lib/infer/infer/lib/python/inferlib/jwlib.py", line 35, in start
    raise e
subprocess.CalledProcessError: Command '[u'/opt/infer-linux64-v0.16.0/lib/infer/infer/lib/python/inferlib/../../../bin/infer', u'capture', u'--continue', u'--', u'javac', u'-d', u'/root/apps/Backend/Elis2Services/build/classes/main', u'-g', u'-encoding', u'ISO-8859-1', u'-sourcepath', u'/root/apps/Backend/Elis2Services/build/tmp/compileJava/emptySourcePathRef', u'-classpath', ...

Internal Error:   /opt/infer-linux64-v0.16.0/lib/infer/infer/bin/../lib/python/infer.py
  --debug --no-filtering -j 4 --project-root /root/apps --out
  /root/apps/infer-out -- ./gradlew --debug clean build 
  exited with code 1
Error backtrace:
Raised at file "string.ml", line 142, characters 16-31
Called from file "src/string.ml", line 402, characters 12-33
Called from file "src/string.ml", line 411, characters 11-33
Re-raised at file "base/Die.ml" (inlined), line 26, characters 8-56
Called from file "base/Die.ml", line 32, characters 6-39
Called from file "integration/Driver.ml", line 164, characters 2-16
Called from file "integration/Driver.ml", line 282, characters 6-409
Called from file "integration/Driver.ml", line 304, characters 2-29
Called from file "infer.ml", line 20, characters 2-36
Called from file "infer.ml", line 131, characters 8-54

Run the command again with `--keep-going` to try and ignore this error.

```

**Comment by jvillard** [comment]
@hmusavi this may have been fixed since 0.16.0. Can you try to repro in the current master? If it still happens please let us know how we can reproduce the error. Thanks!

**Comment by hmusavi** [comment]
0.17.0 does not report these errors. Thank you.
