### ISSUE TITLE
Internal Error: xited with code 1

### ISSUE THREAD

**Issue by kQly** [facebook/infer#1303]
ryan@liyq24 Example % infer --version
Infer version v0.17.0
Copyright 2009 - present Facebook. All Rights Reserved.
ryan@liyq24 Example % infer -- xcodebuild -workspace YQDemo.xcworkspace -scheme YQDemo-Example -configuration Debug -sdk iphoneos -UseModernBuildSystem=YES
Capturing in xcodebuild mode...
Traceback (most recent call last):
  File "/usr/local/Cellar/infer/0.17.0/lib/infer/infer/bin/../lib/python/infer.py", line 203, in <module>
    main()
  File "/usr/local/Cellar/infer/0.17.0/lib/infer/infer/bin/../lib/python/infer.py", line 133, in main
    initial_args = initial_argparser.parse_args(to_parse)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1705, in parse_args
    args, argv = self.parse_known_args(args, namespace)
TypeError: 'NoneType' object is not iterable
Internal Error:   /usr/local/Cellar/infer/0.17.0/lib/infer/infer/bin/../lib/python/infer.py
  -j 8 --project-root /Users/ryan/Documents/project/Demo/YQDemo/Example --out
  /Users/ryan/Documents/project/Demo/YQDemo/Example/infer-out -- xcodebuild
  -workspace YQDemo.xcworkspace -scheme YQDemo-Example -configuration Debug
  -sdk iphoneos -UseModernBuildSystem=YES:
  exited with code 1
Error backtrace:
Raised at file "string.ml", line 145, characters 16-31
Called from file "string.ml" (inlined), line 149, characters 17-46
Called from file "src/string.ml", line 407, characters 12-33
Called from file "src/string.ml", line 416, characters 11-33
Re-raised at file "base/Die.ml", line 26, characters 8-56
Called from file "integration/Driver.ml", line 171, characters 2-16
Called from file "integration/Driver.ml", line 272, characters 6-409
Called from file "integration/Driver.ml", line 323, characters 2-29
Called from file "base/Utils.ml", line 398, characters 16-20
Called from file "scuba/ScubaLogging.ml", line 66, characters 29-44
Called from file "infer.ml", line 20, characters 2-36
Called from file "base/Utils.ml", line 398, characters 16-20
Called from file "scuba/ScubaLogging.ml", line 66, characters 29-44
Called from file "infer.ml", line 137, characters 8-54

Run the command again with `--keep-going` to try and ignore this error.

**Comment by XVilka** [comment]
Should be already fixed in git - please try to compile from the sources or just wait until 1.0 released for the binaries.

**Comment by MicroKibaco** [comment]
### 1. Questioin

>  The Same Error With me！ and then I dont know how to deal with it！

### 2. Mac

![image](https://user-images.githubusercontent.com/17723631/108618416-d2afe000-73d2-11eb-998c-2598af3bff94.png)


### 3. Command

```java
 infer -- ./gradlew -Pis_dev=true -Pis_stage=true :app:assembleDebug -PinstantfixEnable=true --gradle-user-home /Users/xxxxx/Documents/test/android/build/build/.gradle/com.xxx.xxx.xxx --stacktrace
```

 

### 4. infer

Infer version v0.17.0

### 5. platform

Android

### 6. Log

```java
Capturing in gradle mode...
Running and capturing gradle compilation...
Traceback (most recent call last):
  File "/usr/local/Cellar/infer/0.17.0/lib/infer/infer/bin/../lib/python/infer.py", line 203, in <module>
    main()
  File "/usr/local/Cellar/infer/0.17.0/lib/infer/infer/bin/../lib/python/infer.py", line 185, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/usr/local/Cellar/infer/0.17.0/lib/infer/infer/lib/python/inferlib/capture/gradle.py", line 212, in capture
    (build_code, (verbose_out, _)) = util.get_build_output(self.build_cmd)
  File "/usr/local/Cellar/infer/0.17.0/lib/infer/infer/lib/python/inferlib/capture/util.py", line 23, in get_build_output
    proc = subprocess.Popen(build_cmd, stdout=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Internal Error:   /usr/local/Cellar/infer/0.17.0/lib/infer/infer/bin/../lib/python/infer.py
  -j 8 --project-root /Users/xxxxxxxx/Documents/xxxxxxxx --out
  /Users/xxxxxxxx/Documents/xxxxxxxx/infer-out -- ./gradlew
  -Pis_dev=true -Pis_stage=true :app:assembleDebug -PinstantfixEnable=true
  --gradle-user-home
  /Users/xxxxxxxx/Documents/test/android/build/build/.gradle/com.xxxxxxxx.xxxxxxxx.client
  --stacktrace:
  exited with code 1
Error backtrace:
Raised at file "string.ml", line 145, characters 16-31
Called from file "string.ml" (inlined), line 149, characters 17-46
Called from file "src/string.ml", line 407, characters 12-33
Called from file "src/string.ml", line 416, characters 11-33
Re-raised at file "base/Die.ml", line 26, characters 8-56
Called from file "integration/Driver.ml", line 171, characters 2-16
Called from file "integration/Driver.ml", line 272, characters 6-409
Called from file "integration/Driver.ml", line 323, characters 2-29
Called from file "base/Utils.ml", line 398, characters 16-20
Called from file "scuba/ScubaLogging.ml", line 66, characters 29-44
Called from file "infer.ml", line 20, characters 2-36
Called from file "base/Utils.ml", line 398, characters 16-20
```

**Comment by MicroKibaco** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
