### ISSUE TITLE
xcodebuild failed

### ISSUE THREAD

**Issue by roywu01** [facebook/infer#146]
Please help

Traceback (most recent call last):
  File "/home/pharos/infer/infer/bin/infer", line 168, in <module>
    main()
  File "/home/pharos/infer/infer/bin/infer", line 143, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/home/pharos/infer/infer/bin/../lib/capture/xcodebuild.py", line 27, in gen_instance
    return XcodebuildCapture(*args)
  File "/home/pharos/infer/infer/bin/../lib/capture/xcodebuild.py", line 37, in __init__
    subprocess.check_output(['xcrun', '--find', 'clang']).strip()
  File "/usr/local/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
pharos@pharos-CM1435:~$ infer -- gradle
pharos@pharos-CM1435:~$ infer -- xcodebuild
Traceback (most recent call last):
  File "/home/pharos/infer/infer/bin/infer", line 168, in <module>
    main()
  File "/home/pharos/infer/infer/bin/infer", line 143, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/home/pharos/infer/infer/bin/../lib/capture/xcodebuild.py", line 27, in gen_instance
    return XcodebuildCapture(*args)
  File "/home/pharos/infer/infer/bin/../lib/capture/xcodebuild.py", line 37, in __init__
    subprocess.check_output(['xcrun', '--find', 'clang']).strip()
  File "/usr/local/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by martinoluca** [comment]
Hello @roywu01,
Do you have Xcode installed on your computer?
If it is installed, can you please check the output of `xcrun --version`?

Thanks.

**Comment by roywu01** [comment]
Thanks for you response.
I use Linux OS, so I can't install Xcode on it.
I'll use Mac to build it , or is there any way to build Xcode-project on Linus?

Thanks.

**Comment by anthonymonori** [comment]
@roywu01 You can't use Apple developer tools on Linux, because they were build to run on OS X. You would have to run a mac in order to analyse Xcode projects using infer or any other tool for that matter.

Please report back after you tried replicating this on a Mac, otherwise I propose to close this issue.

**Comment by roywu01** [comment]
Sorry, I don't have a Mac.
I think the reason of unable to build Xcode projects is I don't install Xcode on my computer just like what you said.
Thanks for your response, please close this issue.
