### ISSUE TITLE
Get stuck when using infer on android app project with gradle

### ISSUE THREAD

**Issue by wanyukang** [facebook/infer#165]
I have the latest version of infer (Infer version git-37a4709a0f2be7b23a29950a2d6345040b67b8eb), and I build the android app with gradlew(2.4).
In the beginning infer works fine, /infer-out/captured, /infer-out/classnames, /infer-out/sources have some output file about the android project. But after about 10 mins, the gradle build log get stuck on the Terminal, and no more output file increase in the /infer-out dir. 
After 1 hour only one file in /infer-out/captured growing bigger(in 1 hour grows to 348MB), it's name is AboutActivity.java.cfg, so I had to stop running infer.
Any suggestion would be helpful.

**Comment by cjtcwyk** [comment]
the log atfer stop infer.

Traceback (most recent call last):
  File "/Users/wanyukang/git/infer/infer/bin/infer", line 168, in <module>
    main()
  File "/Users/wanyukang/git/infer/infer/bin/infer", line 143, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/Users/wanyukang/git/infer/infer/bin/../lib/capture/gradle.py", line 75, in capture
    return util.run_commands(cmds)
  File "/Users/wanyukang/git/infer/infer/bin/../lib/capture/util.py", line 40, in run_commands
    if not cmd.start():
  File "/Users/wanyukang/git/infer/infer/bin/inferlib.py", line 689, in start
    if self.capture() == os.EX_OK:
  File "/Users/wanyukang/git/infer/infer/bin/inferlib.py", line 451, in capture
    return self.run_infer_frontend()
  File "/Users/wanyukang/git/infer/infer/bin/inferlib.py", line 442, in run_infer_frontend
    self.args.analyzer
  File "/Users/wanyukang/git/infer/infer/bin/inferlib.py", line 349, in run_command
    return subprocess.check_call(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 537, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1357, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 478, in _eintr_retry_call
    return func(*args)

**Comment by jeremydubreil** [comment]
Do you know how big is the file AboutActivity.java ?

**Comment by cjtcwyk** [comment]
@jeremydubreil not a big file, about 7kb

**Comment by sblackshear** [comment]
I'm guessing it's an infinite loop in the Java frontend--is there any way you could send us the file, or (even better) the project and the command you're running to build it?

**Comment by cjtcwyk** [comment]
@sblackshear sorry can't send the whole product codes, but one file AboutActivity.java maybe is Allowed. I will send the file to your mailbox, and the command I'm running is infer -- ./gradlew clean build

**Comment by shbi** [comment]
I too and having this issue 
after about 30 mins i stopped execution
^CTraceback (most recent call last):
  File "/Users/jschneider/Downloads/infer-osx-v0.4.0/infer/bin/infer", line 180, in <module>
    main()
  File "/Users/jschneider/Downloads/infer-osx-v0.4.0/infer/bin/infer", line 144, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/Users/jschneider/Downloads/infer-osx-v0.4.0/infer/bin/../lib/capture/gradle.py", line 83, in capture
    return util.run_commands(cmds)
  File "/Users/jschneider/Downloads/infer-osx-v0.4.0/infer/bin/../lib/capture/util.py", line 40, in run_commands
    if not cmd.start():
  File "/Users/jschneider/Downloads/infer-osx-v0.4.0/infer/bin/inferlib.py", line 692, in start
    if self.capture() == os.EX_OK:
  File "/Users/jschneider/Downloads/infer-osx-v0.4.0/infer/bin/inferlib.py", line 478, in capture
    return self.run_infer_frontend()
  File "/Users/jschneider/Downloads/infer-osx-v0.4.0/infer/bin/inferlib.py", line 469, in run_infer_frontend
    self.args.analyzer
  File "/Users/jschneider/Downloads/infer-osx-v0.4.0/infer/bin/inferlib.py", line 376, in run_command
    return subprocess.check_call(cmd)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1384, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

cat /tmp/mrc.ocu/infer-out/toplevel.log
[INFO] Running command /Users/jschneider/Downloads/infer-osx-v0.4.0/infer/bin/infer -- ./gradlew app:assembleDevDebug -x lint
[INFO] Path to infer script /Users/jschneider/Downloads/infer-osx-v0.4.0/infer/bin/infer (/Users/jschneider/Downloads/infer-osx-v0.4.0/infer/bin/infer)
[INFO] Infer version v0.4.0
Copyright 2009 - present Facebook. All Rights Reserved.


[INFO] Platform: Darwin-14.5.0-x86_64-i386-64bit
[INFO] PATH=/Users/jschneider/.opam/4.01.0/bin:/Users/jschneider/Downloads/infer-osx-v0.4.0/infer/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jschneider/Library/Android/sdk/platform-tools:/Applications/ccollab_client/
[INFO] SHELL=/bin/zsh
[INFO] PWD=/tmp/mrc.ocu
[INFO] Running with:

------------------------------------------------------------
Gradle 2.4
------------------------------------------------------------

Build time:   2015-05-05 08:09:24 UTC
Build number: none
Revision:     5c9c3bc20ca1c281ac7972643f1e2d190f2c943c

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.4 compiled on April 29 2014
JVM:          1.8.0_51 (Oracle Corporation 25.51-b03)
OS:           Mac OS X 10.10.5 x86_64

**Comment by shbi** [comment]
if it helps any 
ps
  PID TTY           TIME CMD
  746 ttys000    0:08.82 -zsh
  748 ttys001    0:02.15 -zsh
52620 ttys001    3:32.34 /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/bin/java -XX:MaxPermSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xmx1024m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /Users/jschneider/.gradle/wrapper/dists/gradle-2.4-all/3i2gobhdl0fm2tosnn15g540i0/gradle-2.4/lib/gradle-launcher-2.4.jar org
53164 ttys001    0:00.42 /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Users/jschneider/Downloads/infer-osx-v0.4.0/infer/bin/infer -- ./gradlew app:assembleDevDebug -x lint
53556 ttys001    2:23.76 /Users/jschneider/Downloads/infer-osx-v0.4.0/infer/bin/InferJava -project_root /private/tmp/mrc.ocu -results_dir /private/tmp/mrc.ocu/infer-out -verbose_out /var/folders/y9/k3528dds1ts_ymh1j05cpzc40000gp/T/javac__c5Gwq.out -models /Users/jschneider/Downloads/infer-osx-v0.4.0/infer/bin/../lib/java/models.jar -no-static_final

**Comment by shbi** [comment]
Also if it helps, ran with --debug a few times, it always hangs on the same file,
It's a package-info.java file

**Comment by sblackshear** [comment]
I haven't been able to reproduce this issue with the file from @wanyukang. @shbi, would you mind sending the package-info.java file that is causing trouble for you?

**Comment by shbi** [comment]
I'm not sure if it was the file that was causing trouble it was just the last one that printed out with --debug
I'll have to find time to run it again to see which particular one it was but it was just a simple package info file, no special characters.

/*
 * copywrite, same as in every other file
 */

/**
 * just a javadoc, no parameters, links ect
 */
package com...;

**Comment by sblackshear** [comment]
Makes sense--I tried running on several pacakge-info files and everything worked fine. Let me know if there's a small (or large) example exhibiting the issue that you can share.

**Comment by SylarDu** [comment]
I met the same issue, related logs as following
^CTraceback (most recent call last):
  File "/home/android/infer-linux64-v0.4.0/infer/bin/infer", line 180, in <module>
    main()
  File "/home/android/infer-linux64-v0.4.0/infer/bin/infer", line 144, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/home/android/infer-linux64-v0.4.0/infer/bin/../lib/capture/gradle.py", line 83, in capture
    return util.run_commands(cmds)
  File "/home/android/infer-linux64-v0.4.0/infer/bin/../lib/capture/util.py", line 40, in run_commands
    if not cmd.start():
  File "/home/android/infer-linux64-v0.4.0/infer/bin/inferlib.py", line 692, in start
    if self.capture() == os.EX_OK:
  File "/home/android/infer-linux64-v0.4.0/infer/bin/inferlib.py", line 478, in capture
    return self.run_infer_frontend()
  File "/home/android/infer-linux64-v0.4.0/infer/bin/inferlib.py", line 469, in run_infer_frontend
    self.args.analyzer
  File "/home/android/infer-linux64-v0.4.0/infer/bin/inferlib.py", line 376, in run_command
    return subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1376, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

**Comment by LiJunyang** [comment]
I met the same issue, gradle 2.4
I met the same issue, related logs as following
^CTraceback (most recent call last):
  File "/Users/lijunyang/Downloads/infer-osx-v0.4.0/infer/bin/infer", line 180, in <module>
    main()
  File "/Users/lijunyang/Downloads/infer-osx-v0.4.0/infer/bin/infer", line 144, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/Users/lijunyang/Downloads/infer-osx-v0.4.0/infer/bin/../lib/capture/gradle.py", line 82, in capture
    cmds = self.get_inferJ_commands(util.get_build_output(self.build_cmd))
  File "/Users/lijunyang/Downloads/infer-osx-v0.4.0/infer/bin/../lib/capture/util.py", line 31, in get_build_output
    (verbose_out_chars, _) = proc.communicate()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 791, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

in mac os
help .....

**Comment by LiJunyang** [comment]
i meet this before .but after i clean my project, it solves now...

**Comment by sblackshear** [comment]
Good to hear! Does cleaning solve for anyone else?

If anyone has a small example exhibiting this problem that they can send, please let me know and I will take a look.

**Comment by sblackshear** [comment]
This should be fixed in the latest release. Please let us know if not.
