### ISSUE TITLE
Javac '-d', 'eprecation'

### ISSUE THREAD

**Issue by giacgbj** [facebook/infer#179]
Environment:
* infer git-5104d852eec5d30da8cd68ae6b6a2fb4e31764a8
* Java 1.7.0_71
* Maven 3.3.3
* Python 2.7.10

I installed the latest version of infer manually on Mac OS X following the guide https://github.com/facebook/infer/blob/master/INSTALL.md .

Plugin configuration:
```
<plugin>
    <groupId>com.anthemengineering.mojo</groupId>
    <artifactId>infer-maven-plugin</artifactId>
    <version>0.1.0</version>
    <configuration>
        <download>false</download>
    </configuration>
    <executions>
        <execution>
            <phase>verify</phase>
            <id>infer</id>
            <goals>
                <goal>infer</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

Error:
```
Javac compilation error with: 

['javac', '-g', '-cp', u'/Applications/infer/bin/../annotations/processor.jar:[OMISSIS]:', '-d', 'eprecation', '-sourcepath', '[OMISSIS]', '-s', '/Users/jhack/workspace/uniserv/uniserv-contract/target/generated-sources/annotations', '-g', '-target', '1.7', '-source', '1.7', '-encoding', 'US-ASCII', '-Xlint:all', [OMISSIS], '-J-Duser.language=en']

javac: directory not found: eprecation
Usage: javac <options> <source files>
use -help for a list of possible options
Traceback (most recent call last):
  File "/Applications/infer/bin/infer", line 180, in <module>
    main()
  File "/Applications/infer/bin/infer", line 144, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/Applications/infer/bin/../lib/capture/mvn.py", line 64, in capture
    return util.run_commands(cmds)
  File "/Applications/infer/bin/../lib/capture/util.py", line 40, in run_commands
    if not cmd.start():
  File "/Applications/infer/bin/inferlib.py", line 692, in start
    if self.capture() == os.EX_OK:
  File "/Applications/infer/bin/inferlib.py", line 476, in capture
    javac_status = self.compile()
  File "/Applications/infer/bin/inferlib.py", line 473, in compile
    return self.javac.run()
  File "/Applications/infer/bin/jwlib.py", line 80, in run
    subprocess.check_call(failing_cmd)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['javac', '-g', '-cp', u'/Applications/infer/bin/../annotations/processor.jar:[OMISSIS]:', '-d', 'eprecation', '-sourcepath', '[OMISSIS]', '-g', '-target', '1.7', '-source', '1.7', '-encoding', 'US-ASCII', '-Xlint:all', [OMISSIS], '-J-Duser.language=en']' returned non-zero exit status 2
```

As you can see
```
'-d', 'eprecation'
```
is used instead of
```
'-deprecation'
```

**Comment by sblackshear** [comment]
Thanks for reporting; that was a silly mistake on our part! Fixed in 62b57827c83a59f5b72b4ed8518db8534ddca61d.
