### ISSUE TITLE
[android]Too many open files & returned non-zero exit status 2

### ISSUE THREAD

**Issue by wowsershan** [facebook/infer#195]
I use infer -- ./gradlew build      and after about 8min then:
Fatal error: exception Sys_error("/Users/lm/project/android_workplace/********/app/build/intermediates/exploded-aar/com.mogujie/user/1.2.17/jars/classes.jar: Too many open files")
Traceback (most recent call last):
  File "/Users/lm/project/infer_workplace/infer-osx-v0.4.0/infer/bin/infer", line 180, in <module>
    main()
  File "/Users/lm/project/infer_workplace/infer-osx-v0.4.0/infer/bin/infer", line 144, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/Users/lm/project/infer_workplace/infer-osx-v0.4.0/infer/bin/../lib/capture/gradle.py", line 83, in capture
    return util.run_commands(cmds)
  File "/Users/lm/project/infer_workplace/infer-osx-v0.4.0/infer/bin/../lib/capture/util.py", line 40, in run_commands
    if not cmd.start():
  File "/Users/lm/project/infer_workplace/infer-osx-v0.4.0/infer/bin/inferlib.py", line 692, in start
    if self.capture() == os.EX_OK:
  File "/Users/lm/project/infer_workplace/infer-osx-v0.4.0/infer/bin/inferlib.py", line 478, in capture
    return self.run_infer_frontend()
  File "/Users/lm/project/infer_workplace/infer-osx-v0.4.0/infer/bin/inferlib.py", line 469, in run_infer_frontend
    self.args.analyzer
  File "/Users/lm/project/infer_workplace/infer-osx-v0.4.0/infer/bin/inferlib.py", line 385, in run_command
    raise e
subprocess.CalledProcessError: Command '[u'/Users/lm/project/infer_workplace/infer-osx-v0.4.0/infer/bin/InferJava', u'-project_root', '/Users/lm/project/android_workplace/Minicooper4android', u'-results_dir', u'/Users/lm/project/android_workplace/Minicooper4android/infer-out', u'-verbose_out', '/var/folders/2r/7hc18jz1091_jg7_8jcnqlhr0000gn/T/javac_qWbfkP.out', u'-models', u'/Users/lm/project/infer_workplace/infer-osx-v0.4.0/infer/bin/../lib/java/models.jar', u'-no-static_final']' returned non-zero exit status 2

**Comment by giljulio** [comment]
+1

**Comment by jvillard** [comment]
This looks like the same issue as #22. You can check how to increase the maximum number of open files on osx as suggested on that issue. Let me know if that helps.

**Comment by wowsershan** [comment]
@jvillard 
I do like this 
sysctl -w kern.maxfiles=20480
sysctl -w kern.maxfilesperproc=22480
ulimit -S -n 2048
It does not work then I set 100 times larger num it does not work too

**Comment by cristianoc** [comment]
Looks like more recent version of OS X need heavier changes and a restart:
  http://apple.itsprite.com/applehow-to-properly-increase-ulimit-n-on-lion/

**Comment by wowsershan** [comment]
@cristianoc solve the problem,3ks

**Comment by jvillard** [comment]
@wowsershan can you please close the issue?

**Comment by wowsershan** [comment]
@jvillard ok, first use issue-.-|||

**Comment by jvillard** [comment]
@wowsershan no problem, thanks :)

**Comment by xukai186** [comment]
@wowsershan  How to solve the problem? 3ks
