### ISSUE TITLE
inferAnalyze stuck at 100% for hours and seems stop print dots.

### ISSUE THREAD

**Issue by tony-zhou** [facebook/infer#223]
Analyze the same project with infer 0.4, it takes about 1 hours. But with infer 0.5, it has already taken more than 5 hours and inferAnalyze still stuck at 100%. 
Would the inferAnalyze fall in the infinite loop and cannot finish itself ?
Could the infer print the process more detail instead of print dots ?

Starting analysis (Infer version v0.5.0)
Computing dependencies... 100%
Analyzing 1264 clusters....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................^Cmake: *** Deleting file `cl908'
make: *** Deleting file `cl915'
Traceback (most recent call last):
  File "/Users/tony/Develop/infer/infer-osx-v0.5.0/infer/bin/infer", line 180, in <module>
make: *** Deleting file `cl916'
make: *** Deleting file `cl932'
make: *** Deleting file `cl400'
    main()
  File "/Users/tony/Develop/infer/infer-osx-v0.5.0/infer/bin/infer", line 166, in main
    analysis.analyze_and_report()
  File "/Users/tony/Develop/infer/infer-osx-v0.5.0/infer/lib/python/inferlib/analyze.py", line 549, in analyze_and_report
    if self.analyze() == os.EX_OK:
  File "/Users/tony/Develop/infer/infer-osx-v0.5.0/infer/lib/python/inferlib/analyze.py", line 458, in analyze
    self.args.analyzer
  File "/Users/tony/Develop/infer/infer-osx-v0.5.0/infer/lib/python/inferlib/analyze.py", line 230, in run_command
    return subprocess.check_call(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1384, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
make: *** [cl400] Interrupt: 2
localhost:Trunk tony$ make: *** [cl908] Interrupt: 2
make: *** [cl915] Interrupt: 2
make: *** [cl916] Interrupt: 2
make: *** [cl932] Interrupt: 2

**Comment by martinoluca** [comment]
Hello @tony-zhou,
do you have an example we can run to reproduce this problem?

Thanks.

**Comment by tony-zhou** [comment]
Hi @martinoluca ,
Sorry I cannot provide the project source code. Is there the parameter I can add when run infer to print more detail. If possible I will try to provide the log for analyze

**Comment by cristianoc** [comment]
There's a fix that might be related in https://github.com/facebook/infer/commit/43ee904a1f1098d0ab3ddbeb8a8e84102d00f1c1.
It requires building Infer from the latest sources.

**Comment by sblackshear** [comment]
The fix is now in the latest release.
