### ISSUE TITLE
Running into a bug after installing Infer

### ISSUE THREAD

**Issue by MatthewBennington** [facebook/infer#266]
Hello I'm trying to get Infer working on my machine, I've got it built, but when I try to analyze the files in the infer/examples directory, I get the following error:

```
mttjone@dev-dsk-mttjone-2c-i-16d04bcc] infer -- javac Hello.java                                                                                                                                       ~/src/infer-0.6.0/examples/java_hello
ERROR: failure during compilation command.
You can run the failing compilation command again by copy-pasting the
lines below in your terminal:

"""
python <<EOF
import subprocess
cmd = ['javac', '-g', '-cp', u'/local/home/mttjone/src/infer-0.6.0/infer/lib/python/inferlib/../../../lib/java/processor.jar', '-d', '/local/home/mttjone/src/infer-0.6.0/examples/java_hello', u'Hello.java', '-J-Duser.language=en', u'-AclassSourceMapOutputFilename=/tmp/classSourceMap_IsLWmh.json']
subprocess.check_call(cmd)
EOF
"""

error: Exception thrown while constructing Processor object: com/facebook/infer/annotprocess/CollectSuppressWarnings : Unsupported major.minor version 52.0
```

When I follow those instructions I get the following error:
```

mttjone@dev-dsk-mttjone-2c-i-16d04bcc] python <<EOF                                                                                                                                                    ~/src/infer-0.6.0/examples/java_hello
heredoc> import subprocess
heredoc> cmd = ['javac', '-g', '-cp', u'/local/home/mttjone/src/infer-0.6.0/infer/lib/python/inferlib/../../../lib/java/processor.jar', '-d', '/local/home/mttjone/src/infer-0.6.0/examples/java_hello', u'Hello.java', '-J-Duser.language=en', u'-AclassSourceMapOutputFilename=/tmp/classSourceMap_IsLWmh.json']
heredoc>
heredoc> subprocess.check_call(cmd)
heredoc> EOF
error: Exception thrown while constructing Processor object: com/facebook/infer/annotprocess/CollectSuppressWarnings : Unsupported major.minor version 52.0
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/path/to/python/Python27/Python27-6729.0-0/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['javac', '-g', '-cp', u'/local/home/mttjone/src/infer-0.6.0/infer/lib/python/inferlib/../../../lib/java/processor.jar', '-d', '/local/home/mttjone/src/infer-0.6.0/examples/java_hello', u'Hello.java', '-J-Duser.language=en', u'-AclassSourceMapOutputFilename=/tmp/classSourceMap_IsLWmh.json']' returned non-zero exit status 1
```

**Comment by sblackshear** [comment]
Almost certainly related to ac5f092653fbc6209a0c5bba91bf0d7bf0b7f749...

Would you mind pasting the output of `javac -version`?

**Comment by MatthewBennington** [comment]
That made me realize that I hadn't added javac to my path correctly, so it was calling JDK6. That being said it's now using 8 and I'm getting the similar error:

```
mttjone@dev-dsk-mttjone-2c-i-16d04bcc] infer -- javac Hello.java                                                                                                                                       ~/src/infer-0.6.0/examples/java_hello
ERROR: failure during compilation command.
You can run the failing compilation command again by copy-pasting the
lines below in your terminal:

"""
python <<EOF
import subprocess
cmd = ['javac', '-g', '-cp', u'/local/home/mttjone/src/infer-0.6.0/infer/lib/python/inferlib/../../../lib/java/processor.jar', '-d', '/local/home/mttjone/src/infer-0.6.0/examples/java_hello', u'Hello.java', '-J-Duser.language=en', u'-AclassSourceMapOutputFilename=/tmp/classSourceMap_8fvGy8.json']
subprocess.check_call(cmd)
EOF
"""

warning: The following options were not recognized by any processor: '[classSourceMapOutputFilename]'
Hello.java:22: error: package Pointers does not exist
    Pointers.A a = Pointers.mayReturnNull(10);
            ^
Hello.java:22: error: cannot find symbol
    Pointers.A a = Pointers.mayReturnNull(10);
                   ^
  symbol:   variable Pointers
  location: class Hello
Hello.java:28: error: package Pointers does not exist
    Pointers.A a = Pointers.mayReturnNull(rng.nextInt());
            ^
Hello.java:28: error: cannot find symbol
    Pointers.A a = Pointers.mayReturnNull(rng.nextInt());
                   ^
  symbol:   variable Pointers
  location: class Hello
Hello.java:34: error: cannot find symbol
    OutputStream stream = Resources.allocateResource();
                          ^
  symbol:   variable Resources
  location: class Hello
5 errors
```

For completeness:` javac 1.8.0_72`

**Comment by jvillard** [comment]
@MatthewBennington this looks like a different error. You need the following command to run the example you are trying to run:

```
infer -- javac Pointers.java Resources.java Hello.java
```

**Comment by MatthewBennington** [comment]
Thanks jvillard, that works. Why wasn't what I was running working? Can you point me to some documentation?

**Comment by jvillard** [comment]
@MatthewBennington There's a Hello.java in the examples/ folder that compiles as you were trying. The one in examples/hello_java/ is a bit more involved. It's documented [here](https://github.com/facebook/infer/blob/master/examples/README).

**Comment by MatthewBennington** [comment]
Thanks!
