### ISSUE TITLE
Can not build with gradle

### ISSUE THREAD

**Issue by liuyangc3** [facebook/infer#281]
in my java project root path.
```
[root@web]# /opt/infer-linux64-v0.7.0/infer/bin/infer -- gradle clean dev war
```
output
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 474, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 29: ordinal not in range(128)
Logged from file infer, line 134

Running and capturing gradle compilation...
10:03:53.937 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
10:03:53.946 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
10:04:04.324 [ERROR] [system.err] Note: /data1/jenkins/workspace/web/nxin-farm-web/src/main/java/com/nxin/farm/common/dao/impl/BaseDaoImpl.java uses or overrides a deprecated API.
10:04:04.325 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
10:04:04.325 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
10:04:04.325 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
Traceback (most recent call last):
  File "/opt/infer-linux64-v0.7.0/infer/bin/infer", line 171, in <module>
    main()
  File "/opt/infer-linux64-v0.7.0/infer/bin/infer", line 136, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/opt/infer-linux64-v0.7.0/infer/lib/python/inferlib/capture/gradle.py", line 84, in capture
    cmds = self.get_infer_commands(util.get_build_output(self.build_cmd))
  File "/opt/infer-linux64-v0.7.0/infer/lib/python/inferlib/capture/gradle.py", line 78, in get_infer_commands
    java_args)
  File "/opt/infer-linux64-v0.7.0/infer/lib/python/inferlib/capture/util.py", line 26, in create_infer_command
    analyze.get_javac_args(['javac'] + javac_arguments))
  File "/opt/infer-linux64-v0.7.0/infer/lib/python/inferlib/analyze.py", line 182, in get_javac_args
    args = map(lambda arg: '-g' if '-g:' in arg else arg, javac_args)
  File "/opt/infer-linux64-v0.7.0/infer/lib/python/inferlib/analyze.py", line 182, in <lambda>
    args = map(lambda arg: '-g' if '-g:' in arg else arg, javac_args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 25: ordinal not in range(128)
```
but if I only use `gradle dev war`, it works fine

errors in `logging` moudle and `inferlib/analyze.py`
but this error didn't show me which file that infer is trying to decode .
so any help? how fix this

**Comment by jvillard** [comment]
hi @liuyangc3, we're working on fixing a similar issue, we'll keep you posted.

**Comment by liuyangc3** [comment]
@jvanzyl 

lib/python/inferlib/analyze.py
```
def get_javac_args(args):
    javac_args = args[detect_javac(args) + 1:]

    if len(javac_args) == 0:
        return None
    else:
        # replace any -g:.* flag with -g to preserve debugging symbols
        args = map(lambda arg: '-g' if '-g:' in arg else arg, javac_args)
        # skip -Werror
        args = filter(lambda arg: arg != '-Werror', args)
        return arg
```
I found `args` has non acsii chars,

in my case args  is  ['javac', '-d', '/data1/jenkins/workspace/\xe7\x94\xb0\xe8\x81\x94\xe7\xbd\x91'...]

**Comment by jvillard** [comment]
This issue should be fixed in the current master (dc52ce8158c51e22e16c36997324f6b089d6b560).

**Comment by jvillard** [comment]
closing optimistically. Please re-open if the issue still exists.

**Comment by liuyangc3** [comment]
hi, @jvillard 
I notice infer v8.0 releaseed, and fixed [dc52ce8](https://github.com/facebook/infer/commit/dc52ce8158c51e22e16c36997324f6b089d6b560)

so I tried again on my gradle project
```
[root@bj-zb-manage nxin-farm-web]# /opt/infer-linux64-v0.8.0/infer/bin/infer -- gradle clean dev
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 25: ordinal not in range(128)
Logged from file infer, line 140
Running and capturing gradle compilation...
Traceback (most recent call last):
  File "/opt/infer-linux64-v0.8.0/infer/bin/infer", line 178, in <module>
    main()
  File "/opt/infer-linux64-v0.8.0/infer/bin/infer", line 142, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/opt/infer-linux64-v0.8.0/infer/lib/python/inferlib/capture/gradle.py", line 87, in capture
    cmds = self.get_infer_commands(util.get_build_output(self.build_cmd))
  File "/opt/infer-linux64-v0.8.0/infer/lib/python/inferlib/capture/util.py", line 27, in get_build_output
    return verbose_out_chars.split('\n')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 222: ordinal not in range(128)
```
maybe the encode issues needs be fixed more more than one place.

**Comment by liuyangc3** [comment]
I open a new issue for this

**Comment by jvillard** [comment]
@liuyangc3 what's the full path from where you're running infer? The one ending "nxin-farm-web".

Also, can you paste the output of `locale` here?
