### ISSUE TITLE
Exceptions are raised because of utf-8 string in function names.

### ISSUE THREAD

**Issue by kstreee** [facebook/infer#287]
I try to analyze some java project which includes functions that use 한글 (Hangul) as function name.
한글 (Hangul) is used rarely for test functions like, ```test_ABC_성공()``` (it means ```test_ABC_success()```)

In that case, I encountered following python exceptions.

* This exception is reported at first time when I run Infer with the utf-8 string (not English) functions.
```
Starting analysis (Infer version v0.7.0)
Computing dependencies... 100%
Analyzing 318 clusters....................................................................................................................................................................................
..........................................................................................................................................
Traceback (most recent call last):
  File "/infer/infer/bin/infer", line 170, in <module>
    main()
  File "/infer/infer/bin/infer", line 156, in main
    analysis.analyze_and_report()
  File "/opt/infer-linux64-v0.7.0/infer/lib/python/inferlib/analyze.py", line 577, in analyze_and_report
    report_status = self.create_report()
  File "/opt/infer-linux64-v0.7.0/infer/lib/python/inferlib/analyze.py", line 534, in create_report
    issues.clean_json(self.args, json_report)
  File "/opt/infer-linux64-v0.7.0/infer/lib/python/inferlib/issues.py", line 131, in clean_json
    rows = utils.load_json_from_path(json_report)
  File "/opt/infer-linux64-v0.7.0/infer/lib/python/inferlib/utils.py", line 135, in load_json_from_path
    return json.load(file_in, encoding=config.LOCALE)
  File "/usr/lib/python2.7/json/__init__.py", line 286, in load
    return loads(fp.read(),
  File "/usr/lib/python2.7/codecs.py", line 674, in read
    return self.reader.read(size)
  File "/usr/lib/python2.7/codecs.py", line 480, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xed in position 10615: invalid continuation byte
```

* This exception is reported when I run it again.
```
Traceback (most recent call last):
  File "/infer/infer/bin/infer", line 170, in <module>
    main()
  File "/infer/infer/bin/infer", line 120, in main
    analyze.remove_infer_out(args.infer_out)
  File "/opt/infer-linux64-v0.7.0/infer/lib/python/inferlib/analyze.py", line 191, in remove_infer_out
    shutil.rmtree(infer_out, True)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 241, in rmtree
    fullname = os.path.join(path, name)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 80: ordinal not in range(128)
```

I run it in docker which is built by [Dockerfile](https://github.com/facebook/infer/blob/master/docker/Dockerfile), but I checked that same exceptions are reported on my local Ubuntu environment.

P.S. Line numbers in above call trace could not exactly same with others log, because I added some debug code in python code.

**Comment by kstreee** [comment]
It is hard to set an environment and code which triggers above exceptions. I will figure out how to set an environment to reproduce the above bug, and share it on this issue.

**Comment by jvillard** [comment]
Hi @kstreee, have you tried with the latest master? there's a good chance that this issue was solved in dc52ce8158c51e22e16c36997324f6b089d6b560. Let me know if it works for you.

**Comment by kstreee** [comment]
@jvillard I tested above bug using ```Infer version v0.7.0-379d185```, but exceptions are reported again.
Some UTF-8 characters are handled well by Infer, but some other characters causes the exceptions. I will find reasons of it more.

**Comment by adamhowardprice** [comment]
I am also experiencing this issue. bump thread

**Comment by jvillard** [comment]
@kstreee, @adamhowardprice What's your locale? (`locale`)

I cannot reproduce this locally, so a minimal example would help.

**Comment by jvillard** [comment]
Also, what's the full path of the current directory you are running Infer from?

@adamhowardprice which trace do you get? @kstreee reported two different ones.

Thanks!

**Comment by jvillard** [comment]
Actually, I can reproduce this if the locale is set to something that doesn't support the characters in the files that are analysed, eg `LC_ALL=C` and some function names have utf-8 names. Working on a fix.

**Comment by adamhowardprice** [comment]
@jvillard The Infer binary lives in `/Users/spotify-buildagent/.vulcan/cache/infer-0.7.0-osx-x86_64.zip-7476817ede427b9e2a2586f57d09a216fa353117/extracted/infer/lib/python/infer` and is being invoked from `/Users/spotify-buildagent/buildAgent/work/c2c5a1e10baf8cc9`

locale:
```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by adamhowardprice** [comment]
My trace:

```
Traceback (most recent call last):
[23:24:52]W:	 [Step 2/3]   File "/Users/spotify-buildagent/.vulcan/cache/infer-0.7.0-osx-x86_64.zip-7476817ede427b9e2a2586f57d09a216fa353117/extracted/infer/lib/python/infer", line 170, in <module>
[23:24:52]W:	 [Step 2/3]     main()
[23:24:52]W:	 [Step 2/3]   File "/Users/spotify-buildagent/.vulcan/cache/infer-0.7.0-osx-x86_64.zip-7476817ede427b9e2a2586f57d09a216fa353117/extracted/infer/lib/python/infer", line 156, in main
[23:24:52]W:	 [Step 2/3]     analysis.analyze_and_report()
[23:24:52]W:	 [Step 2/3]   File "/Users/spotify-buildagent/.vulcan/cache/infer-0.7.0-osx-x86_64.zip-7476817ede427b9e2a2586f57d09a216fa353117/extracted/infer/lib/python/inferlib/analyze.py", line 587, in analyze_and_report
[23:24:52]W:	 [Step 2/3]     issues.print_and_save_errors(json_report, bugs_out)
[23:24:52]W:	 [Step 2/3]   File "/Users/spotify-buildagent/.vulcan/cache/infer-0.7.0-osx-x86_64.zip-7476817ede427b9e2a2586f57d09a216fa353117/extracted/infer/lib/python/inferlib/issues.py", line 233, in print_and_save_errors
[23:24:52]W:	 [Step 2/3]     text = _text_of_report_list(errors)
[23:24:52]W:	 [Step 2/3]   File "/Users/spotify-buildagent/.vulcan/cache/infer-0.7.0-osx-x86_64.zip-7476817ede427b9e2a2586f57d09a216fa353117/extracted/infer/lib/python/inferlib/issues.py", line 182, in _text_of_report_list
[23:24:52]W:	 [Step 2/3]     line,
[23:24:52]W:	 [Step 2/3]   File "/Users/spotify-buildagent/.vulcan/cache/infer-0.7.0-osx-x86_64.zip-7476817ede427b9e2a2586f57d09a216fa353117/extracted/infer/lib/python/inferlib/source.py", line 82, in build_source_context
[23:24:52]W:	 [Step 2/3]     for line in source_file:
[23:24:52]W:	 [Step 2/3]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 687, in next
[23:24:52]W:	 [Step 2/3]     return self.reader.next()
[23:24:52]W:	 [Step 2/3]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 618, in next
[23:24:52]W:	 [Step 2/3]     line = self.readline()
[23:24:52]W:	 [Step 2/3]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 533, in readline
[23:24:52]W:	 [Step 2/3]     data = self.read(readsize, firstline=True)
[23:24:52]W:	 [Step 2/3]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 480, in read
[23:24:52]W:	 [Step 2/3]     newchars, decodedbytes = self.decode(data, self.errors)
[23:24:52]W:	 [Step 2/3] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
[23:24:52]W:	 [Step 2/3] 
[23:24:52]W:	 [Step 2/3] 
[23:24:52]W:	 [Step 2/3]      [31mCOMMAND FAILED: infer -- xcodebuild NSUnbufferedIO\=YES SPT_EXTRA_CFLAGS\=-fno-modules CODE_SIGN_IDENTITY\= CODE_SIGNING_REQUIRED\=NO -workspace Spotify\+features.xcworkspace -scheme Spotify -configuration Release -sdk iphoneos -derivedDataPath build/infer-dd [0m
[23:24:52]W:	 [Step 2/3] Process exited with code 1
```
