### ISSUE TITLE
Python import missing.

### ISSUE THREAD

**Issue by kstreee** [facebook/infer#288]
Following exception is raised for most current version of Infer,

```
Traceback (most recent call last):
  File "/home/skim/Documents/infer/infer/bin/infer", line 178, in <module>
    main()
  File "/home/skim/Documents/infer/infer/bin/infer", line 142, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/home/skim/Documents/infer/infer/lib/python/inferlib/capture/mvn.py", line 78, in capture
    cmds = self.get_infer_commands(util.get_build_output(self.build_cmd))
  File "/home/skim/Documents/infer/infer/lib/python/inferlib/capture/mvn.py", line 48, in get_infer_commands
    capture = jwlib.create_infer_command(self.args, javac_args)
NameError: global name 'jwlib' is not defined
```

```from inferlib import jwlib``` is required because of [this line](https://github.com/facebook/infer/blob/9d080cadb19d02ee5ba45893ee03de113e7333e5/infer/lib/python/inferlib/capture/mvn.py#L48).

**Comment by kstreee** [comment]
I think that Python code in Infer should have test code too.
