### ISSUE TITLE
gradle build failed

### ISSUE THREAD

**Issue by liuyangc3** [facebook/infer#304]
hi, @jvillard 
see   #281   I commented 
```
[root@bj-zb-manage nxin-farm-web]# /opt/infer-linux64-v0.8.0/infer/bin/infer -- gradle clean dev
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 25: ordinal not in range(128)
Logged from file infer, line 140
Running and capturing gradle compilation...
Traceback (most recent call last):
  File "/opt/infer-linux64-v0.8.0/infer/bin/infer", line 178, in <module>
    main()
  File "/opt/infer-linux64-v0.8.0/infer/bin/infer", line 142, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/opt/infer-linux64-v0.8.0/infer/lib/python/inferlib/capture/gradle.py", line 87, in capture
    cmds = self.get_infer_commands(util.get_build_output(self.build_cmd))
  File "/opt/infer-linux64-v0.8.0/infer/lib/python/inferlib/capture/util.py", line 27, in get_build_output
    return verbose_out_chars.split('\n')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 222: ordinal not in range(128)
maybe the encode issues needs be fixed more more than one place.
```

**Comment by jvillard** [comment]
@liuyangc3 what's the full path from where you're running infer? The one ending "nxin-farm-web".

Also, can you paste the output of `locale` here?

**Comment by liuyangc3** [comment]
@jvillard 

yes some Chinese in path

**Comment by jvillard** [comment]
@liuyangc3 python2 is quite picky about utf-8 in your environment. Right now we don't support running from a path with utf8 in it, see this old issue: #76 

I'm closing this as a duplicate of #76, but please feel free to comment on that issue if you want to add something.

**Comment by jvillard** [comment]
We plan to fix this at some point, hopefully in the coming months, by the way. For now you can move your project somewhere else to analyze it.
