### ISSUE TITLE
--continue not working

### ISSUE THREAD

**Issue by hmijail** [facebook/infer#315]
When running infer --reactive --continue -- clang blah.c , it fails with a 
`Fatal error: exception Unix.Unix_error(Unix.ENOENT, "stat", "/Users/mija/programming/infer-out/.start")`

infer 0.8 installed with brew on Mac OS X 10.11.3

Full trace:
```
$ rm -r infer-out/ ; infer --reactive --continue --debug --frontend-debug -- clang inf_recur.c
[INFO:infer:133] Running command /usr/local/bin/infer --reactive --continue --debug --frontend-debug -- clang inf_recur.c
[INFO:infer:135] Path to infer script /usr/local/bin/infer (/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/infer)
[INFO:infer:136] Infer version v0.8.0
Copyright 2009 - present Facebook. All Rights Reserved.


[INFO:infer:137] Platform: Darwin-15.3.0-x86_64-i386-64bit
[INFO:infer:138] PATH=/opt/local/libexec/ccache:/opt/local/bin:/opt/local/sbin:/Users/mija/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
[INFO:infer:139] SHELL=/bin/bash
[INFO:infer:140] PWD=/Users/mija/programming
[INFO:make.py:059] Running command [u'clang', u'inf_recur.c'] with env:
{'LESS': '-WaiMJR', 'LC_CTYPE': 'UTF-8', 'TERM_PROGRAM_VERSION': '361.1', 'LOGNAME': 'mija', 'USER': 'mija', 'QTDIR': '/opt/local', 'PATH': '/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/../../../lib/wrappers:/opt/local/libexec/ccache:/opt/local/bin:/opt/local/sbin:/Users/mija/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin', 'PS1': '\\[\\e[1m\\]\\#:\\w$ \\[\\e[0m\\]', 'DISPLAY': '/private/tmp/com.apple.launchd.hbXCmESwLn/org.macosforge.xquartz:0', 'TERM_PROGRAM': 'Apple_Terminal', 'INFOPATH': '/opt/local/share/info:', 'TERM': 'xterm-color', 'SHELL': '/bin/bash', 'SHLVL': '1', 'SECURITYSESSIONID': '186a7', 'XPC_FLAGS': '0x0', 'DBUS_LAUNCHD_SESSION_BUS_SOCKET': '/private/tmp/com.apple.launchd.Hc20sCaezu/unix_domain_listener', 'TMPDIR': '/var/folders/2d/1kly9t3s23bclpxgs6l342vc0000gs/T/', 'MANPATH': '/opt/local/share/man:/usr/local/man:', 'HOME': '/Users/mija', 'TERM_SESSION_ID': '0477ED6F-9075-4D60-8FB8-DA2C1F4A7A41', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.Ri7wvs7Q4F/Listeners', 'XPC_SERVICE_NAME': '0', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.cpuMHHHl1j/Render', u'FCP_DEBUG_MODE': u'1', 'INFER_OLD_PATH': '/opt/local/libexec/ccache:/opt/local/bin:/opt/local/sbin:/Users/mija/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin', '_': '/usr/local/bin/infer', 'LSCOLORS': 'hxFxCxDxBxegedabagacad', u'INFER_RESULTS_DIR': u'/Users/mija/programming/infer-out', 'OLDPWD': '/Users/mija', 'CLICOLOR': '1', '__CF_USER_TEXT_ENCODING': '0x1F9:0x0:0xF', 'PWD': '/Users/mija/programming', u'FCP_INFER_FRONTEND_ARGS': u'-project_root /Users/mija/programming -debug'}
[INFO:infer:146] Capture phase was successful
[INFO:analyze.py:267] Starting analysis

/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/../../../bin/InferAnalyze -results_dir /Users/mija/programming/infer-out -makefile Makefile -allow_specs_cleanup -inferconfig_home /Users/mija/programming -models /usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/../../../lib/java/models.jar -developer_mode -html -dotty -print_types -trace_error -print_buckets -notest -reactive -continue -project_root /Users/mija/programming

Starting analysis (Infer version v0.8.0)
Fatal error: exception Unix.Unix_error(Unix.ENOENT, "stat", "/Users/mija/programming/infer-out/.start")
[ERROR:analyze.py:216] Failure during create_makefile, original command was

[u'infer', u'-g', u'-a', u'infer', u'--', u'javac']


Traceback (most recent call last):
  File "/usr/local/bin/infer", line 178, in <module>
    main()
  File "/usr/local/bin/infer", line 164, in main
    analysis.analyze_and_report()
  File "/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/analyze.py", line 481, in analyze_and_report
    if self.analyze() == os.EX_OK:
  File "/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/analyze.py", line 381, in analyze
    self.args.analyzer
  File "/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/analyze.py", line 218, in run_command
    raise e
subprocess.CalledProcessError: Command '[u'/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/../../../bin/InferAnalyze', u'-results_dir', u'/Users/mija/programming/infer-out', u'-makefile', u'Makefile', u'-allow_specs_cleanup', u'-inferconfig_home', '/Users/mija/programming', u'-models', u'/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/../../../lib/java/models.jar', u'-developer_mode', u'-html', u'-dotty', u'-print_types', u'-trace_error', u'-print_buckets', u'-notest', u'-reactive', u'-continue', u'-project_root', '/Users/mija/programming']' returned non-zero exit status 2
```

**Comment by jvillard** [comment]
Thanks, it looks like `--reactive --continue` crashes when infer hasn't been run previously. We're working on a fix, I'll keep you updated. In the meantime, you can run infer without `--continue` the first time around, then `--continue` should work as expected.
