### ISSUE TITLE
Complile filed

### ISSUE THREAD

**Issue by wisenight** [facebook/infer#327]
Hi, Sir

I use infer 0.8 to build my code, and got below exception.

But I have no idea about this.

Traceback (most recent call last):
  File "/infer/infer/bin/infer", line 180, in <module>
    main()
  File "/infer/infer/bin/infer", line 166, in main
    analysis.analyze_and_report()
  File "/opt/infer-linux64-v0.8.0/infer/lib/python/inferlib/analyze.py", line 481, in analyze_and_report
    if self.analyze() == os.EX_OK:
  File "/opt/infer-linux64-v0.8.0/infer/lib/python/inferlib/analyze.py", line 360, in analyze
    self.args.analyzer
  File "/opt/infer-linux64-v0.8.0/infer/lib/python/inferlib/analyze.py", line 218, in run_command
    raise e
subprocess.CalledProcessError: Command '[u'/opt/infer-linux64-v0.8.0/infer/lib/python/inferlib/../../../bin/InferAnalyze', u'-results_dir', u'/jenkins/cms_daily_infer/infer-out', u'-allow_specs_cleanup', u'-inferconfig_home', '/jenkins/cms_daily_infer', u'-models', u'/opt/infer-linux64-v0.8.0/infer/lib/python/inferlib/../../../lib/java/models.jar', u'-project_root', '/jenkins/cms_daily_infer']' returned non-zero exit status -9
Build step 'Execute shell' marked build as failure
Archiving artifacts

**Comment by jvillard** [comment]
Hi @wisenight,

Can you please provide more information? Please include:
- the command you used to run infer
- the full output (please use https://gist.github.com/ or equivalent)
- the contents of toplevel.log (also on https://gist.github.com/)

Thanks!

**Comment by jvillard** [comment]
please re-open with more information
