### ISSUE TITLE
 execute infer :: ValueError: unknown locale: UTF-8

### ISSUE THREAD

**Issue by Hellengo** [facebook/infer#358]
log:
SpeedXworkstation:~ qa$ brew install infer
==> Downloading https://homebrew.bintray.com/bottles/infer-0.8.1.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/infer-0.8.1.el_capitan.bottle.tar.gz
==> Pouring infer-0.8.1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/infer/0.8.1: 11,840 files, 696.6M
SpeedXworkstation:~ qa$ infer
Traceback (most recent call last):
  File "/usr/local/bin/infer", line 18, in <module>
    from inferlib import analyze, config, utils
  File "/usr/local/Cellar/infer/0.8.1/libexec/infer/lib/python/inferlib/analyze.py", line 26, in <module>
    from . import config, issues, utils
  File "/usr/local/Cellar/infer/0.8.1/libexec/infer/lib/python/inferlib/config.py", line 18, in <module>
    CODESET = locale.getlocale(locale.LC_CTYPE)[1]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 562, in getlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

**Comment by jvillard** [comment]
what's the output of `locale`?

**Comment by Hellengo** [comment]
thx,   
vi  .bash_profile
add    export LANG=en_US.UTF-8

**Comment by jberdine** [comment]
Looks like your locale is misconfigured.  It should have a value such as 'en_US.UTF-8'.
