### ISSUE TITLE
iOS build failed，i can't find same question

### ISSUE THREAD

**Issue by cocoaroger** [facebook/infer#403]
Hello
I use the command:
>infer -- xcodebuild clean build -workspace xxx.xcworkspace -scheme xxx -configuration Debug -sdk iphonesimulator

then show me the error，i can't find any answer:
>
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 22: ordinal not in range(128)
Logged from file infer, line 141
Traceback (most recent call last):
  File "/Users/iSouBu/Desktop/infer-osx-v0.8.1/infer/bin/infer", line 183, in <module>
    main()
  File "/Users/iSouBu/Desktop/infer-osx-v0.8.1/infer/bin/infer", line 147, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/Users/iSouBu/Desktop/infer-osx-v0.8.1/infer/lib/python/inferlib/capture/xcodebuild.py", line 72, in capture
    subprocess.check_call(self.cmd, env=self.get_envvars())
  File "/Users/iSouBu/Desktop/infer-osx-v0.8.1/infer/lib/python/inferlib/capture/xcodebuild.py", line 57, in get_envvars
    util.get_clang_frontend_envvars(self.args)
  File "/Users/iSouBu/Desktop/infer-osx-v0.8.1/infer/lib/python/inferlib/capture/util.py", line 155, in get_clang_frontend_envvars
    env_vars['FCP_INFER_FRONTEND_ARGS'] = ' '.join(frontend_args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 22: ordinal not in range(128)

**Comment by jvillard** [comment]
What version of infer are you using? This should be fixed in 0.9.0.

**Comment by cocoaroger** [comment]
Thanks, My current version is 0.8.1.
