### ISSUE TITLE
I can't run infer on my macbook

### ISSUE THREAD

**Issue by onion4** [facebook/infer#421]
This is my error log,pls help me.Tks!

caoxiaodeMacBook-Pro:app-mararun-android caoxiao$ infer -- ./gradlew build
Traceback (most recent call last):
  File "/usr/local/bin/infer", line 183, in <module>
    main()
  File "/usr/local/bin/infer", line 131, in main
    touch_if_present=not args.continue_capture)
  File "/usr/local/Cellar/infer/0.8.1/libexec/infer/lib/python/inferlib/analyze.py", line 182, in reset_start_file
    open(start_path, 'w').close()
IOError: [Errno 13] Permission denied: u'/Users/caoxiao/Dropbox/mara/app-mararun-android/infer-out/.start'
caoxiaodeMacBook-Pro:app-mararun-android caoxiao$ sudo infer -- ./gradlew build
Password:
Running and capturing gradle compilation...
Traceback (most recent call last):
  File "/usr/local/bin/infer", line 183, in <module>
    main()
  File "/usr/local/bin/infer", line 147, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/usr/local/Cellar/infer/0.8.1/libexec/infer/lib/python/inferlib/capture/gradle.py", line 87, in capture
    cmds = self.get_infer_commands(util.get_build_output(self.build_cmd))
  File "/usr/local/Cellar/infer/0.8.1/libexec/infer/lib/python/inferlib/capture/util.py", line 30, in get_build_output
    proc = subprocess.Popen(build_cmd, stdout=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
caoxiaodeMacBook-Pro:app-mararun-android caoxiao$

**Comment by liweijian** [comment]
Wrap the log with markdown tag would make us easier.

And we need more info:
1. How would you install infer? (brew or compile the source code yourself?)
2. Can you build the code by just `./gradlew build` without _infer_?
3. Try to copy your code to another directory(Not in the dropbox file), and `./gradlew clean`, than try again?

**Comment by martinoluca** [comment]
Hello @onion4,
From the logs seems there are wrong permissions set for the `infer-out` folder.

Thanks
