### ISSUE TITLE
ValueError: unknown locale: UTF-8

### ISSUE THREAD

**Issue by modLX4** [facebook/infer#445]
Traceback (most recent call last):
  File "/usr/local/bin/infer", line 18, in <module>
    from inferlib import analyze, config, utils
  File "/usr/local/Cellar/infer/0.8.1/libexec/infer/lib/python/inferlib/analyze.py", line 26, in <module>
    from . import config, issues, utils
  File "/usr/local/Cellar/infer/0.8.1/libexec/infer/lib/python/inferlib/config.py", line 18, in <module>
    CODESET = locale.getlocale(locale.LC_CTYPE)[1]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 562, in getlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

**Comment by xennygrimmato** [comment]
You seem to be using version 0.8.1.
This issue was fixed in [49adf59](https://github.com/facebook/infer/commit/49adf5933260836c17bc29b90a6ade50a803a83d).

**Comment by jvillard** [comment]
Please reopen if there is still an issue with 0.9.2 (try `brew update && brew upgrade infer`).
