### ISSUE TITLE
ValueError: unknown locale: UTF-8

### ISSUE THREAD

**Issue by tudorturcanu** [facebook/infer#447]
Traceback (most recent call last):
  File "/usr/local/bin/../Cellar/infer/0.9.2/bin/../lib/infer/infer/lib/python/infer.py", line 18, in <module>
    from inferlib import analyze, config, utils
  File "/usr/local/Cellar/infer/0.9.2/lib/infer/infer/lib/python/inferlib/analyze.py", line 26, in <module>
    from . import config, issues, utils
  File "/usr/local/Cellar/infer/0.9.2/lib/infer/infer/lib/python/inferlib/config.py", line 19, in <module>
    CODESET = locale.getlocale(locale.LC_CTYPE)[1]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 562, in getlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

**Comment by jvillard** [comment]
Thanks for the report. What does `locale` report to you?

**Comment by tudorturcanu** [comment]
hey, tnx for your support. 

locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

**Comment by xennygrimmato** [comment]
You can try: `export LC_ALL=en_US.UTF-8`

**Comment by tudorturcanu** [comment]
it works. tnx.
