### ISSUE TITLE
Infer fails immediately on 0.9.2

### ISSUE THREAD

**Issue by kageiit** [facebook/infer#452]
Getting this error immediately after running infer 0.9.2 on an android project. 0.8.4 works correctly on the project

```
Starting analysis (Infer version v0.9.2)

legend:
  "F" analyzing a file
  "." analyzing a procedure

Infer version v0.9.2
Copyright 2009 - present Facebook. All Rights Reserved.
Warning: unexpected attribute found: Code
Warning: unexpected attribute found: Code
Warning: unexpected attribute found: Code
Warning: unexpected attribute found: Code
Warning: unexpected attribute found: Code
Warning: unexpected attribute found: Code
Warning: unexpected attribute found: Code
Warning: unexpected attribute found: Code
Warning: unexpected attribute found: Code
Warning: unexpected attribute found: Code
Warning: unexpected attribute found: Code
Warning: unexpected attribute found: Code
Fatal error: exception Unix.Unix_error(Unix.ENOENT, "stat", "/example/buck-out/bin/library/lib__src_main__classes/infer/.start")
Failed to execute: /usr/local/Cellar/infer/0.9.2/lib/infer/infer/lib/python/inferlib/../../../bin/../lib/python/infer.py -r --analyzer eradicate --buck --infer_cache /example/infer-out/cache --multicore 8 --out /example/infer-out --project_root /example -- javac -source 7 -target 7 -sourcepath  -g -Xlint:deprecation -Xlint:-options -Xlint:-unchecked -Werror -Xmaxerrs 1000000 -d /example/buck-out/bin/library/lib__src_main__classes -classpath /example/buck-out/gen/.okbuck/cache/com.android.support.support-annotations-24.1.1.jar.jar:/example/buck-out/gen/.okbuck/cache/com.jakewharton.rxrelay.rxrelay-1.1.0.jar.jar:/example/buck-out/gen/.okbuck/cache/com.example.android.android-4.1.1.5.jar.jar:/example/buck-out/gen/.okbuck/cache/com.example.lib2-1.0.1.jar.jar:/example/buck-out/gen/.okbuck/cache/com.example.lib1-1.7.0.jar.jar:/example/buck-out/gen/.okbuck/cache/io.reactivex.rxjava-1.1.8.jar.jar @buck-out/gen/library/__src_main__srcs
Traceback (most recent call last):
  File "/example/infer_pRbRHX.py", line 6, in <module>
    subprocess.check_call(cmd)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'/usr/local/Cellar/infer/0.9.2/lib/infer/infer/lib/python/inferlib/../../../bin/infer', u'--buck', u'--analyzer', u'eradicate', u'--infer_cache', u'/example/infer-out/cache', '--', 'javac', '-source', '7', '-target', '7', '-sourcepath', '', '-g', '-Xlint:deprecation', '-Xlint:-options', '-Xlint:-unchecked', '-Werror', '-Xmaxerrs', '1000000', '-d', '/example/buck-out/bin/library/lib__src_main__classes', '-classpath', '/example/buck-out/gen/.okbuck/cache/com.android.support.support-annotations-24.1.1.jar.jar:/example/buck-out/gen/.okbuck/cache/com.jakewharton.rxrelay.rxrelay-1.1.0.jar.jar:/example/buck-out/gen/.okbuck/cache/com.example.android.android-4.1.1.5.jar.jar:/example/buck-out/gen/.okbuck/cache/com.example.lib2-1.0.1.jar.jar:/example/buck-out/gen/.okbuck/cache/com.example.lib1-1.7.0.jar.jar:/example/buck-out/gen/.okbuck/cache/io.reactivex.rxjava-1.1.8.jar.jar', '@buck-out/gen/library/__src_main__srcs']' returned non-zero exit status 2
```

**Comment by xennygrimmato** [comment]
Which version of Java are you using?

**Comment by kageiit** [comment]
```
java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

**Comment by jeremydubreil** [comment]
Does it happen deterministically ? 

It could it be a race condition between:
- https://github.com/facebook/infer/blob/master/infer/lib/python/inferlib/analyze.py#L200
and
- https://github.com/facebook/infer/blob/master/infer/src/backend/DB.ml#L356
?

**Comment by jberdine** [comment]
The "jar jar" classpath entries such as com.android.support.support-annotations-24.1.1.jar.jar look fishy to me.  Is infer itself responsible for the duplicate extensions?

**Comment by kageiit** [comment]
It is happening 100% of the time. we are on buck head

**Comment by kageiit** [comment]
This seems to be only happening when running with `-r`

**Comment by jeremydubreil** [comment]
Yes, that is right. Using `--reactive`, I am able to reproduce the issue.

**Comment by jberdine** [comment]
Optimistically closing, please reopen if this problem remains with 0.9.4.
