### ISSUE TITLE
Does not seem to work with JNI methods

### ISSUE THREAD

**Issue by mohadian** [facebook/infer#475]
It seems Infer crashes if the main project is referencing a JNI method from one of the sub modules

library module
```
Class A {
  public native int jniMethod();
}
```

main app module{
```
Class B {
  private A refrence;

  private void methodAB(){
    reference.jniMethod();
  }
}
```

warning: The following options were not recognized by any processor: '[classSourceMapOutputFilename]'
/app/B.java:XYZ: error: cannot find symbol
        reference.jniMethod();
                  ^
  symbol:   method jniMethod()
  location: variable refrence of type A
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
Traceback (most recent call last):
  File "/usr/local/bin/infer", line 183, in <module>
    main()
  File "/usr/local/bin/infer", line 147, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/usr/local/Cellar/infer/0.8.1/libexec/infer/lib/python/inferlib/capture/gradle.py", line 89, in capture
    return util.run_compilation_commands(cmds, clean_cmd)
  File "/usr/local/Cellar/infer/0.8.1/libexec/infer/lib/python/inferlib/capture/util.py", line 40, in run_compilation_commands
    if cmd.start() != os.EX_OK:
  File "/usr/local/Cellar/infer/0.8.1/libexec/infer/lib/python/inferlib/jwlib.py", line 195, in start
    self._compile()
  File "/usr/local/Cellar/infer/0.8.1/libexec/infer/lib/python/inferlib/jwlib.py", line 270, in _compile
    return self.javac.run()
  File "/usr/local/Cellar/infer/0.8.1/libexec/infer/lib/python/inferlib/jwlib.py", line 164, in run
    subprocess.check_call(failing_cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)

------
[INFO:infer:137] Infer version v0.8.1
[INFO:gradle.py:046] Running with:

------------------------------------------------------------
Gradle 2.14.1
------------------------------------------------------------

Build time:   2016-07-18 06:38:37 UTC
Revision:     d9e2113d9fb05a5caabba61798bdb8dfdca83719

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_31 (Oracle Corporation 25.31-b07)
OS:           Mac OS X 10.11.6 x86_64

**Comment by mohadian** [comment]
More details
if I comment the `reference.jniMethod();` the infer finishes successfully

**Comment by sblackshear** [comment]
Will this program compile independently of Infer? In your small example, there's a spelling mistake (`refrence` vs `reference`). When I fix this mistake, the program works with both Infer and `javac`.
