### ISSUE TITLE
[crash] InferAnalyze Failed when analyzing my ios project

### ISSUE THREAD

**Issue by GeekMin** [facebook/infer#486]
Today, I use infer to analyze our IOS project:
Capture part is OK, but analyze part is failed:

log here:
[INFO] Capture phrase was successful
[INFO] Starting analysis
[ERROR] Failure during run_makefile, original command was
[u'infer', u'-g', u'infer', u'--', u'javac']

Crash strace:
make: **\* [cl2558] Error 137
make: Target `default' not remade because of errors.
Traceback (most recent call last):
  File "/Users/bensonqin/Documents/infer-osx-v0.9.3/infer/bin/../lib/python/infer.py", line 230, in <module>
    main()
  File "/Users/bensonqin/Documents/infer-osx-v0.9.3/infer/bin/../lib/python/infer.py", line 214, in main
    analysis.analyze_and_report()
  File "/Users/bensonqin/Documents/infer-osx-v0.9.3/infer/lib/python/inferlib/analyze.py", line 537, in analyze_and_report
    elif self.analyze() == os.EX_OK:
  File "/Users/bensonqin/Documents/infer-osx-v0.9.3/infer/lib/python/inferlib/analyze.py", line 428, in analyze
    self.args.analyzer
  File "/Users/bensonqin/Documents/infer-osx-v0.9.3/infer/lib/python/inferlib/analyze.py", line 240, in run_command
    raise e
subprocess.CalledProcessError: Command '[u'make', u'-k', u'-j', '8', u'-s']' returned non-zero exit status 2

A..ha...I build my IOS project... Why the log tells me that "infer --javac"?

**Comment by sblackshear** [comment]
Can you share the command that you are using to run Infer on your project?

**Comment by GeekMin** [comment]
infer  -- xcodebuild -target dailybuildipa -configuration DailyBuild -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

But run twice.. the problem is missing...

**Comment by jberdine** [comment]
Could you try with the current 0.9.4.1 release, which includes much more robust integration with xcodebuild using xcpretty?  Optimistically closing, but please reopen if the problem remains.
