### ISSUE TITLE
Android: subprocess.CalledProcessError

### ISSUE THREAD

**Issue by tuanchauict** [facebook/infer#5]
I got this error. The traceback is:

    Traceback (most recent call last):
      File "/Users/tuanchauict/Data/Software/Dev/infer-osx-v0.1.0/infer/infer/bin/infer", line 142, in <module>
        main()
      File "/Users/tuanchauict/Data/Software/Dev/infer-osx-v0.1.0/infer/infer/bin/infer", line 119, in main
        capture_exitcode = imported_module.gen_instance(args, cmd).capture()
      File "/Users/tuanchauict/Data/Software/Dev/infer-osx-v0.1.0/infer/infer/bin/../lib/capture/gradle.py", line 42, in capture
        return util.run_commands(cmds)
      File "/Users/tuanchauict/Data/Software/Dev/infer-osx-v0.1.0/infer/infer/bin/../lib/capture/util.py", line 34, in run_commands
        if not cmd.start():
      File "/Users/tuanchauict/Data/Software/Dev/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 632, in start
        if self.capture() == os.EX_OK:
      File "/Users/tuanchauict/Data/Software/Dev/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 400, in capture
        return self.run_infer_frontend()
      File "/Users/tuanchauict/Data/Software/Dev/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 391, in run_infer_frontend
        self.args.analyzer
      File "/Users/tuanchauict/Data/Software/Dev/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 318, in run_command
        raise e
    subprocess.CalledProcessError: Command '[u'/Users/tuanchauict/Data/Software/Dev/infer-osx-v0.1.0/infer/infer/bin/InferJava', u'-results_dir', u'/Users/tuanchauict/workspace/Android/Sudoku/infer-out', u'-verbose_out', '/tmp/javac_S_WOLP.out', u'-models', u'/Users/tuanchauict/Data/Software/Dev/infer-osx-v0.1.0/infer/infer/bin/../lib/java/models.jar', u'-no-static_final']' returned non-zero exit status 2

Mac OS 10.10
Java 7 (for Android project)

**Comment by sblackshear** [comment]
Hi Tuan, thanks for the report. Would it be possible for you to share the project you were running on when you encountered this error? 

If not, there should have been a message starting with "Failure during" before the stack trace; that would be helpful as well.

**Comment by tuanchauict** [comment]
Oh, this issue came from the class name $$ like #3 

    Fatal error: exception Invalid_argument("Error : com.tuanchauict.sudoku.MainActivity$$ViewInjector is not a valid name for a class")


We can close it now
