### ISSUE TITLE
Error : keep occurring R.java not found

### ISSUE THREAD

**Issue by omuomugin** [facebook/infer#541]
Hello, Infer team

I'm doing research about analysis tools for Android apps and one of it is this Infer. 
The problem that I have right now is that I can run ```./gradlew build clean```, ```./gradlew clean``` succesfully but when I try to run ```infer -- ./gradlew build clean``` it tells me that infer cannot find R.java.

I'm using v0.9.2, and for example applying Infer on [iosched](https://github.com/google/iosched) `s version 9f38e2d9e6ca81341fecf82d881cf629effb4be2 gives this error.(Also on some other projects too) 
In Addition, my envorionment is MacOS Sierra

 full error log is below

Is this error from Infer? or occurs from other reasons?  
Thank you,

```
javac: file not found: <MYPATH>/iosched/android/build/generated/source/r/mapEditor/debug/android/support/design/R.java
Usage: javac <options> <source files>
use -help for a list of possible options
Traceback (most recent call last):
  File "/usr/local/bin/../Cellar/infer/0.9.2/bin/../lib/infer/infer/lib/python/infer.py", line 228, in <module>
    main()
  File "/usr/local/bin/../Cellar/infer/0.9.2/bin/../lib/infer/infer/lib/python/infer.py", line 190, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/usr/local/Cellar/infer/0.9.2/lib/infer/infer/lib/python/inferlib/capture/gradle.py", line 87, in capture
    return util.run_compilation_commands(cmds, clean_cmd)
  File "/usr/local/Cellar/infer/0.9.2/lib/infer/infer/lib/python/inferlib/capture/util.py", line 40, in run_compilation_commands
    if cmd.start() != os.EX_OK:
  File "/usr/local/Cellar/infer/0.9.2/lib/infer/infer/lib/python/inferlib/jwlib.py", line 264, in start
    self._compile()
  File "/usr/local/Cellar/infer/0.9.2/lib/infer/infer/lib/python/inferlib/jwlib.py", line 338, in _compile
    return self.javac.run()
  File "/usr/local/Cellar/infer/0.9.2/lib/infer/infer/lib/python/inferlib/jwlib.py", line 233, in run
    subprocess.check_call(failing_cmd)
  File "<MYPATH>/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'javac', u'-J-Duser.language=en', u'@<MYPATH>/iosched/infer-out/filelists/gradle_SAo53L.txt', u'@/var/folders/n3/s93xtgws2114_yqxdy6x8xch0000gn/T/javac_args_rQQ5S4']' returned non-zero exit status 2
Failed to execute: /usr/local/bin/../Cellar/infer/0.9.2/bin/../lib/infer/infer/lib/python/infer.py --multicore 4 --out <MYPATH>/iosched/infer-out --project_root /Users/shunsuke/Desktop/college/research/Apps/iosched -- ./gradlew build clean
```

**Comment by omuomugin** [comment]
For additional information, even I update infer to v0.9.4, this still occurs.

just for adding detail
Thank you,

**Comment by jvillard** [comment]
The gradle integration shipped with infer is crude and will run javac on all the files ending in ".java" in gradle's verbose output... If there is no file R.java then that will fail.

You may have more luck with the more robust [uber's gradle plugin for infer](https://github.com/uber-common/infer-plugin).

**Comment by omuomugin** [comment]
@jvillard 
thank you for info. I will take a try.

**Comment by omuomugin** [comment]
Finally I solved the problem.

After running ```gradlew init```, infer started to run successfully. 

Thanks,
