### ISSUE TITLE
Infer infinitely loops/mallocs on certain C files

### ISSUE THREAD

**Issue by dwbuiten** [facebook/infer#555]
# Description

FFMpeg's [matroskadec.c](http://git.videolan.org/?p=ffmpeg.git;a=blob;f=libavformat/matroskadec.c;h=7e74348b2a1b8833ed5fa67fce384b8c430d48d6;hb=HEAD) seems to cause Infer to loops infinitely somewhere in the compiler plugin, I think. You end up seeing things like:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
17156 root      20   0 12.745g 0.011t  10944 R 100.0 40.1  27:21.37 gcc
```

or 

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
25220 root      20   0 22.169g 0.020t  10872 R  99.8 71.6  83:55.72 clang
```

It might actually finish (i.e. not be infinite) but I killed it after 15-20 mins + 22gb mem usage.

Upon CTRL-C, the following traceback is produced:

```
^Cmake: *** Deleting file 'libavformat/matroskadec.o'
Traceback (most recent call last):
  File "/opt/infer-linux64-v0.9.4.1/infer/bin/../lib/python/infer.py", line 203, in <module>
    main()
  File "/opt/infer-linux64-v0.9.4.1/infer/bin/../lib/python/infer.py", line 186, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/opt/infer-linux64-v0.9.4.1/infer/lib/python/inferlib/capture/make.py", line 71, in capture
    subprocess.check_call(cmd, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call

    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
root@59d40e5c7ebe:~/ffmpeg#     return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1384, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
common.mak:60: recipe for target 'libavformat/matroskadec.o' failed
```

# How to Reproduce

Start a fresh Infer docker container, and clone FFmpeg. I tested with 4c63910bdbf04ce4ed80a870d676877fc031df5a.

Reproduction is simple:

```
apt-get install yasm
cd ffmpeg
./configure
infer -- make
```

When it gets to matroskadec.c, it will hit this bug. Could also use `make libavformat/matroskadec.c`.

**Comment by akotulski** [comment]
Interestingly, it works on my mac (both 0.9.4.1 and master) so it may be something system dependent. Do you know which version gcc of docker container uses?

**Comment by dwbuiten** [comment]
I used the standard method of installing (on Linux) using the `Dockerfile` and `run.sh`. Infer version is:

```
# infer --version
Infer version v0.9.4
Copyright 2009 - present Facebook. All Rights Reserved.
```

Tried with both GCC and Clang, which have the following versions inside the Infer container:

```
# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.9.2-10ubuntu13' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Ubuntu 4.9.2-10ubuntu13)
```

```
s# clang -v | head -1
Ubuntu clang version 3.6.0-2ubuntu1 (tags/RELEASE_360/final) (based on LLVM 3.6.0)
Target: x86_64-pc-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/4.9.2
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/5.0.1
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9.2
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.0.1
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.0.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.0.1
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

Some additional info in case it's useful:

```
# uname -a
Linux bfda2a7bd4fb 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 x86_64 x86_64 GNU/Linux
```

```
$ docker --version
Docker version 1.6.2, build 7c8fca2
```

**Comment by jvillard** [comment]
Running on ffmpeg at the specified version with the latest infer (v0.15.0) doesn't infinite loop anymore and the analysis is successful.
