### ISSUE TITLE
OSError: [Errno 2] No such file or directory (Android project)

### ISSUE THREAD

**Issue by sereden** [facebook/infer#60]
I've received ```OSError: [Errno 2] No such file or directory``` trying to execute ```infer -- ./gradlew build``` from your android_hello example:

```
Traceback (most recent call last):
    File "/home/andrii/Android/infer-linux64-v0.1.0/infer/infer/bin/infer", line 142, in <module>
                                                                                      main()

    File "/home/andrii/Android/infer-linux64-v0.1.0/infer/infer/bin/infer", line 119, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()

    File "/home/andrii/Android/infer-linux64-v0.1.0/infer/infer/bin/../lib/capture/gradle.py", line 41, in capture
    cmds = self.get_inferJ_commands(util.get_build_output(self.build_cmd))

    File "/home/andrii/Android/infer-linux64-v0.1.0/infer/infer/bin/../lib/capture/util.py", line 24, in get_build_output
    proc = subprocess.Popen(build_cmd, stdout=subprocess.PIPE)

    File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)

    File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception

    OSError: [Errno 2] No such file or directory
```

It is sad that I have to ```edit the local.properties file to point to the location of your Android SDK```, but your example doesn't contain it. Should I add it manually?

**Comment by sereden** [comment]
Ok. I've found solution. I don't know why, but I do not have ./gradlew, so I have to use ***```infer -- gradle build```***

**Comment by liutingdu** [comment]
Thanks @sereden It's good to know other people had the same problem...

I had to manually create ```local.properties```. The [document](http://fbinfer.com/docs/hello-world.html#hello-world-android) says **Edit** the file, which is really confusing.

**Comment by jvillard** [comment]
@liutingdu Thanks, I've updated the docs to clear that up.
