### ISSUE TITLE
Failed to build Android Project

### ISSUE THREAD

**Issue by don59** [facebook/infer#61]
What I use:

	infer -- ./gradlew build

&I got this:

	don@PC003-Ubuntu:~/workspace/BangBang-Android$ infer -- ./gradlew build
	Traceback (most recent call last):
	  File "/opt/infer-linux64-v0.1.0/infer/infer/bin/infer", line 142, in <module>
	    main()
	  File "/opt/infer-linux64-v0.1.0/infer/infer/bin/infer", line 119, in main
	    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
	  File "/opt/infer-linux64-v0.1.0/infer/infer/bin/../lib/capture/gradle.py", line 41, in capture
	    cmds = self.get_inferJ_commands(util.get_build_output(self.build_cmd))
	  File "/opt/infer-linux64-v0.1.0/infer/infer/bin/../lib/capture/util.py", line 24, in get_build_output
	    proc = subprocess.Popen(build_cmd, stdout=subprocess.PIPE)
	  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
	    errread, errwrite)
	  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
	    raise child_exception
	OSError: [Errno 13] Permission denied

**Comment by akotulski** [comment]
Hi @don59 thanks for reporting!
Does the build command succeed itself?
  ./gradlew build

Do you have permissions to write to ~/workspace/BangBang-Android folder?
ls -ld ~/workspace/BangBang-Android

**Comment by don59** [comment]
don@PC003-Ubuntu:~/workspace/BangBang-Android$ ls -ld ~/workspace/BangBang-Android
	drwxrwxr-x 9 don don 4096  6 15 11:06 /home/don/workspace/BangBang-Android
