### ISSUE TITLE
Invalid_argument("Error : com.packagename.HomeActivity$$InjectAdapter is not a valid name for a class")

### ISSUE THREAD

**Issue by oshamahue** [facebook/infer#63]
Hi,

I exected this 'infer -- ./gradlew build --stacktrace' and  I received the following exception. I use Dagger for DI and I assume InjectAdapter is a generated class for injection. 

```
Fatal error: exception Invalid_argument("Error : com.packagename.HomeActivity$$InjectAdapter is not a valid name for a class")
[ERROR] Failure during frontend, original command was
[u'inferJ', u'-g', u'-a', 'capture', u'javac', '-source', '1.7', '-target', '1.7', '-d'{bunch project jars}]


Traceback (most recent call last):
  File "/Library/infer-osx-v0.1.0/infer/infer/bin/infer", line 142, in <module>
    main()
  File "/Library/infer-osx-v0.1.0/infer/infer/bin/infer", line 119, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/Library/infer-osx-v0.1.0/infer/infer/bin/../lib/capture/gradle.py", line 42, in capture
    return util.run_commands(cmds)
  File "/Library/infer-osx-v0.1.0/infer/infer/bin/../lib/capture/util.py", line 34, in run_commands
    if not cmd.start():
  File "/Library/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 632, in start
    if self.capture() == os.EX_OK:
  File "/Library/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 400, in capture
    return self.run_infer_frontend()
  File "/Library/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 391, in run_infer_frontend
    self.args.analyzer
  File "/Library/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 318, in run_command
    raise e
subprocess.CalledProcessError: Command '[u'/Library/infer-osx-v0.1.0/infer/infer/bin/InferJava', u'-results_dir', u'/Users/haditok/GitHub/Android-app/infer-out', u'-verbose_out', '/var/folders/68/4pkjv9fd743040h3dmj98kbm0000gn/T/javac_KjBTQT.out', u'-models', u'/Library/infer-osx-v0.1.0/infer/infer/bin/../lib/java/models.jar', u'-no-static_final']' returned non-zero exit status 2
```

**Comment by oshamahue** [comment]
I didn't see the opened issue so I am closing as duplicate #3
