### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by baxiang** [facebook/infer#640]
Traceback (most recent call last):
  File "/usr/local/Cellar/infer/0.10.0/lib/infer/infer/bin/../lib/python/report.py", line 47, in <module>
    main()
  File "/usr/local/Cellar/infer/0.10.0/lib/infer/infer/bin/../lib/python/report.py", line 43, in main
    args.issues_json, bugs_out, args.pmd_xml)
  File "/usr/local/Cellar/infer/0.10.0/lib/infer/infer/lib/python/inferlib/issues.py", line 191, in print_and_save_errors
    file_out.write(_pmd_xml_of_issues(errors))
  File "/usr/local/Cellar/infer/0.10.0/lib/infer/infer/lib/python/inferlib/issues.py", line 217, in _pmd_xml_of_issues
    class_name = info[-2:-1][0]
IndexError: list index out of range
** Error running the reporting script:

xcode:8.2.1
python:2.7

**Comment by jeremydubreil** [comment]
@baxiang: What is the top-level analysis command that you are using ?

**Comment by baxiang** [comment]
infer  -- xcodebuild -workspace PuddingPlus.xcworkspace -scheme PuddingPlus  -configuration Debug  clean
infer --pmd-xml -- xcodebuild -workspace PuddingPlus.xcworkspace -scheme PuddingPlus -configuration Debug

**Comment by jeremydubreil** [comment]
Are both commands failing or just the second one ?

**Comment by baxiang** [comment]
remove  --pmd-xml ,the  analysis command success。
add  --pmd-xml print:
.too many issues to display (limit=10 exceeded), please see /Users/roobo/Documents/Pudding_Plus/infer-out/bugs.txt or run `inferTraceBugs` for the remaining issues.

Summary of the reports

          DIRECT_ATOMIC_PROPERTY_ACCESS: 259
                       NULL_DEREFERENCE: 75
                           RETAIN_CYCLE: 39
             PARAMETER_NOT_NULL_CHECKED: 39
                 BAD_POINTER_COMPARISON: 36
                            MEMORY_LEAK: 20
                 ASSIGN_POINTER_WARNING: 13
  REGISTERED_OBSERVER_BEING_DEALLOCATED: 8
                          RESOURCE_LEAK: 5
                  IVAR_NOT_NULL_CHECKED: 1
                STRONG_DELEGATE_WARNING: 1
Traceback (most recent call last):
  File "/usr/local/Cellar/infer/0.10.0/lib/infer/infer/bin/../lib/python/report.py", line 47, in <module>
    main()
  File "/usr/local/Cellar/infer/0.10.0/lib/infer/infer/bin/../lib/python/report.py", line 43, in main
    args.issues_json, bugs_out, args.pmd_xml)
  File "/usr/local/Cellar/infer/0.10.0/lib/infer/infer/lib/python/inferlib/issues.py", line 191, in print_and_save_errors
    file_out.write(_pmd_xml_of_issues(errors))
  File "/usr/local/Cellar/infer/0.10.0/lib/infer/infer/lib/python/inferlib/issues.py", line 217, in _pmd_xml_of_issues
    class_name = info[-2:-1][0]
IndexError: list index out of range
** Error running the reporting script:
**   /usr/local/Cellar/infer/0.10.0/lib/infer/infer/bin/../lib/python/report.py --issues-csv /Users/roobo/Documents/Pudding_Plus/infer-out/report.csv --issues-json /Users/roobo/Documents/Pudding_Plus/infer-out/report.json --pmd-xml --project-root /Users/roobo/Documents/Pudding_Plus --results-dir /Users/roobo/Documents/Pudding_Plus/infer-out
** See error above

**Comment by jvillard** [comment]
Looks like the xml output is assuming some format for the `"procedure_id"` field of the json that doesn't work for ObjC: https://github.com/facebook/infer/blob/master/infer/lib/python/inferlib/issues.py#L215-L218

Thanks for the report, I'll look into it.

**Comment by jvillard** [comment]
@baxiang I cannot reproduce your issue on a simple xcodebuild example. Can you paste your infer-out/report.json?

**Comment by baxiang** [comment]
https://drive.google.com/open?id=0B2FWH0mS2hdhbEhaZUZIOGpVMzg

**Comment by jvillard** [comment]
Thanks for the report @baxiang, this should be fixed in master now.
