### ISSUE TITLE
UnicodeDecodeError if run in a path with UTF-8 characters

### ISSUE THREAD

**Issue by jonan** [facebook/infer#76]
When I run `infer` in a directory with UTF-8 chars in it's name I get the following error:

    Traceback (most recent call last):
      File "/home/jonan/Descargas/infer-linux64-v0.1.0/infer/infer/bin/infer", line 5, in <module>
        import inferlib
      File "/home/jonan/Descargas/infer-linux64-v0.1.0/infer/infer/bin/inferlib.py", line 29, in <module>
        import utils
      File "/home/jonan/Descargas/infer-linux64-v0.1.0/infer/infer/bin/utils.py", line 30, in <module>
        DEFAULT_INFER_OUT = os.path.join(os.getcwd(), 'infer-out')
      File "/usr/lib/python2.7/posixpath.py", line 73, in join
        path += '/' + b
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 22: ordinal not in range(128)

I can fix it changing that line to

    DEFAULT_INFER_OUT = os.path.join(unicode(os.getcwd(), 'utf-8'), 'infer-out')

But I don't think that's a solution

**Comment by irpap** [comment]
Hi @jonan, 
I reproduced this issue, and will take a look at fixing it. Thanks for reporting it.

**Comment by skyuplam** [comment]
+1

**Comment by salomon1184** [comment]
I met this bug too, when the bug will be repaired？
