### ISSUE TITLE
Infer needs a working compilation command to run, anyone can help to solve?

### ISSUE THREAD

**Issue by Huang-Jacky** [facebook/infer#787]
Infer running stoped and throw an exception as below:
*** ERROR Failed to execute compilation command: exited with code 1
*** Command: 'javac' '@/Users/huangjincheng/workarea/mob_dev/andsdk/MobSdk/infer-out/filelists/gradle_eIHKuV.txt' '@/var/folders/lk/lc_q_c9s6hjb06_fv57w290c0000gn/T/args_94016b'
.
.
*** Infer needs a working compilation command to run.
Failed to execute: /usr/local/Cellar/infer/0.12.1/lib/infer/infer/lib/python/inferlib/../../../bin/in
..
...
Traceback (most recent call last):
  File "/usr/local/Cellar/infer/0.12.1/lib/infer/infer/bin/../lib/python/infer.py", line 186, in <module>
    main()
  File "/usr/local/Cellar/infer/0.12.1/lib/infer/infer/bin/../lib/python/infer.py", line 168, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/usr/local/Cellar/infer/0.12.1/lib/infer/infer/lib/python/inferlib/capture/gradle.py", line 88, in capture
    return util.run_compilation_commands(cmds, clean_cmd)
  File "/usr/local/Cellar/infer/0.12.1/lib/infer/infer/lib/python/inferlib/capture/util.py", line 41, in run_compilation_commands
    if cmd.start() != os.EX_OK:
  File "/usr/local/Cellar/infer/0.12.1/lib/infer/infer/lib/python/inferlib/jwlib.py", line 37, in start
    raise e
subprocess.CalledProcessError: Command '[u'/usr/local/Cellar/infer/0.12.1/lib/infer/infer/lib/python/inferlib/../../../bin/infer', u'--analyzer', u'capture', u'--continue', u'--', u'javac', u'-source', u'1.7', u'-target', u'1.7', u'-d', u'/Users/huangjincheng/workarea/mob_dev/andsdk/MobSdk/app/bui..........

**Comment by jvillard** [comment]
What command did you use to run infer? Does the compilation command work on its own, without infer attached?

**Comment by jvillard** [comment]
Please reopen with more information.
