### ISSUE TITLE
Fatal error: exception JBasics.Class_structure_error("Illegal method index (does not refer to a constant method)")

### ISSUE THREAD

**Issue by rmp91** [facebook/infer#88]
I tried to execute "infer -- ant compile". It fails with the following output:
 
```bash
Warning: unexpected attribute found: Code
Warning: unexpected attribute found: Code
Warning: unexpected attribute found: Code
Warning: unexpected attribute found: Code
Warning: unexpected attribute found: Code
Fatal error: exception JBasics.Class_structure_error("Illegal method index (does not refer to a constant method)")
[ERROR] Failure during frontend

Traceback (most recent call last):
  File "/infer-linux64-v0.1.1/infer/infer/bin/infer", line 141, in <module>
    main()
  File "/infer-linux64-v0.1.1/infer/infer/bin/infer", line 118, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/infer-linux64-v0.1.1/infer/infer/bin/../lib/capture/ant.py", line 69, in capture
    return util.run_commands(cmds)
  File "/infer-linux64-v0.1.1/infer/infer/bin/../lib/capture/util.py", line 34, in run_commands
    if not cmd.start():
  File "/infer-linux64-v0.1.1/infer/infer/bin/inferlib.py", line 632, in start
    if self.capture() == os.EX_OK:
  File "/infer-linux64-v0.1.1/infer/infer/bin/inferlib.py", line 400, in capture
    return self.run_infer_frontend()
  File "/infer-linux64-v0.1.1/infer/infer/bin/inferlib.py", line 391, in run_infer_frontend
    self.args.analyzer
  File "/infer-linux64-v0.1.1/infer/infer/bin/inferlib.py", line 318, in run_command
    raise e

```
My project compiles otherwise. 

OS: Ubuntu 14.04
Java version "1.8.0_45"

What should I do?

**Comment by sblackshear** [comment]
Try downgrading to Java 7--Infer currently does not support Java 8 (see the install guide [here](https://github.com/facebook/infer/blob/master/INSTALL.md)).

**Comment by jeremydubreil** [comment]
@rmp91: This is an interesting bug. Thanks for reporting it. It would be great if we could reproduce it in order to fix it upstream in the javalib library used to parse bytecode.

**Comment by MarvinSchramm** [comment]
+1 I have the same thing

**Comment by jvillard** [comment]
tracking Java8 support in #314
