### ISSUE TITLE
running infer on a buck target results in exception

### ISSUE THREAD

**Issue by mkr-plse** [facebook/infer#973]
I have tried infer on simple examples by doing a capture on javac and it works fine. 
For a buck target that successfully builds, when I do a 

     infer capture -- buck build <target>,

 I get the following error: 
 
Capturing in buck mode...
Traceback (most recent call last):
  File "/usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../lib/python/infer.py", line 203, in <module>
    main()
  File "/usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../lib/python/infer.py", line 185, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/usr/local/Cellar/infer/0.15.0/lib/infer/infer/lib/python/inferlib/capture/buck.py", line 89, in capture
    return self.capture_without_flavors()
  File "/usr/local/Cellar/infer/0.15.0/lib/infer/infer/lib/python/inferlib/capture/buck.py", line 267, in capture_without_flavors
    buck_wrapper = bucklib.Wrapper(self.args, self.cmd)
  File "/usr/local/Cellar/infer/0.15.0/lib/infer/infer/lib/python/inferlib/bucklib.py", line 247, in __init__
    self.normalized_targets = get_normalized_targets(buck_args)
  File "/usr/local/Cellar/infer/0.15.0/lib/infer/infer/lib/python/inferlib/bucklib.py", line 100, in get_normalized_targets
    subprocess.check_output(buck_cmd).decode().strip().split('\n'))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Is there some other setup that needs to happen before invoking infer capture? 

Thanks!

**Comment by jberdine** [comment]
Just to clarify, have you tried without the trailing comma: `infer capture -- buck build <target>` ?

**Comment by mkruber** [comment]
The , was just part of this text. I have found the error. 
I had my own install of buck and my actual command was 
    `infer capture -- <path_to_buck_bin>/buck build <target>`

This resulted in the failure of `buck_cmd` at line 100 as it was trying to execute `buck` without the path info. After adding <path_to_buck_bin> to PATH, the problem got resolved. 

Maybe the docs can be updated to avoid this error? 

Thanks!

**Comment by jvillard** [comment]
Thanks for digging into this. I think using the full path to buck provided on the command line would make sense.
