### ISSUE TITLE
Infer/Buck integration error: Cannot set both javac and javacjar

### ISSUE THREAD

**Issue by mkruber** [facebook/infer#976]
When building a target with buck, the build is successful. Doing a `infer capture` on this build results in the following error: 

   ```java.lang.RuntimeException: Cannot create a toolchain: javac-options. Cause: Cannot set both javac and javacjar
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.getOrCreate(DefaultToolchainProvider.java:176)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.getByName(DefaultToolchainProvider.java:109)
	at com.facebook.buck.toolchain.BaseToolchainProvider.getByName(BaseToolchainProvider.java:24)
	at com.facebook.buck.jvm.java.JavaLibraryDescription.createBuildRule(JavaLibraryDescription.java:180)
	at com.facebook.buck.jvm.java.JavaLibraryDescription.createBuildRule(JavaLibraryDescription.java:1)
	at com.facebook.buck.core.rules.transformer.impl.DefaultTargetNodeToBuildRuleTransformer.transform(DefaultTargetNodeToBuildRuleTransformer.java:89)
	at com.facebook.buck.core.rules.resolver.impl.SingleThreadedActionGraphBuilder.lambda$1(SingleThreadedActionGraphBuilder.java:109)
	at com.facebook.buck.core.rules.resolver.impl.SingleThreadedActionGraphBuilder.computeIfAbsent(SingleThreadedActionGraphBuilder.java:85)
	at com.facebook.buck.core.rules.resolver.impl.SingleThreadedActionGraphBuilder.requireRule(SingleThreadedActionGraphBuilder.java:104)
	at com.facebook.buck.core.model.actiongraph.computation.ActionGraphCache$2.visit(ActionGraphCache.java:500)
	at com.facebook.buck.core.model.actiongraph.computation.ActionGraphCache$2.visit(ActionGraphCache.java:1)
	at com.facebook.buck.graph.AbstractBottomUpTraversal.traverse(AbstractBottomUpTraversal.java:51)
	at com.facebook.buck.graph.AbstractBottomUpTraversal.traverse(AbstractBottomUpTraversal.java:34)
	at com.facebook.buck.core.model.actiongraph.computation.ActionGraphCache.createActionGraphSerially(ActionGraphCache.java:503)
	at com.facebook.buck.core.model.actiongraph.computation.ActionGraphCache.createActionGraph(ActionGraphCache.java:379)
	at com.facebook.buck.core.model.actiongraph.computation.ActionGraphCache.getActionGraph(ActionGraphCache.java:228)
	at com.facebook.buck.core.model.actiongraph.computation.ActionGraphCache.getActionGraph(ActionGraphCache.java:122)
	at com.facebook.buck.cli.BuildCommand.createActionGraphAndResolver(BuildCommand.java:1327)
	at com.facebook.buck.cli.BuildCommand.createGraphsAndTargets(BuildCommand.java:492)
	at com.facebook.buck.cli.BuildCommand.executeBuildAndProcessResult(BuildCommand.java:575)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:453)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:419)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:274)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:77)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1181)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:425)
	at com.facebook.buck.cli.Main.main(Main.java:1891)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:55)

Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.facebook.buck.core.exceptions.HumanReadableException: Cannot set both javac and javacjar
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.getOrCreate(DefaultToolchainProvider.java:166)
	... 31 more

Caused by: com.facebook.buck.core.exceptions.HumanReadableException: Cannot set both javac and javacjar
	at com.facebook.buck.jvm.java.AbstractJavacSpec.getJavacSource(AbstractJavacSpec.java:41)
	at com.facebook.buck.jvm.java.JavacSpec.getJavacSource(JavacSpec.java:1)
	at com.facebook.buck.jvm.java.JavaBuckConfig.trackClassUsage(JavaBuckConfig.java:157)
	at com.facebook.buck.jvm.java.JavaBuckConfig.getDefaultJavacOptions(JavaBuckConfig.java:106)
	at com.facebook.buck.jvm.java.toolchain.impl.JavacOptionsProviderFactory.createToolchain(JavacOptionsProviderFactory.java:33)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.createToolchain(DefaultToolchainProvider.java:191)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider.access$1(DefaultToolchainProvider.java:183)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider$1.load(DefaultToolchainProvider.java:64)
	at com.facebook.buck.toolchain.impl.DefaultToolchainProvider$1.load(DefaultToolchainProvider.java:1)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	... 35 more
```

It doesn't look like a buck error as the buck build succeeds independently (even though a `javac_jar` is set to something else in a `.buckconfig` file). Is there a way to address this issue?

**Comment by mkruber** [comment]
@jvillard @jberdine,  even pointing `--java-jar-compiler` to the appropriate jar file causes the same issue. In my `.buckconfig`, the `[tools]->javac_jar` corresponds to `error_prone_ant*.jar` and buck builds without any issues. Any suggestions to overcome this problem when capturing with infer?

**Comment by jvillard** [comment]
If you remove the `[tools]->javac_jar` from your .buckconfig is the capture command happier? If so maybe a solution would be for infer to somehow unset that variable when it calls Buck.

**Comment by mkruber** [comment]
Not having `javac_jar` in `.buckconfig` gets rid of this error but then it breaks the build of the current buck target. Potentially, I can change the way the project under consideration is built internally but am looking for a less intrusive way of running infer.

**Comment by jvillard** [comment]
Do you mean it breaks the build of the buck target when built without infer? Does the infer capture go through successfully when `javac_jar` is not specified?

**Comment by mkruber** [comment]
Yes, that breaks the build of the buck target when built without infer. So, when infer capture happens, the error mentioned in this issue disappears but then the overall build breaks as it does when it is built without infer.

**Comment by jvillard** [comment]
@jeremydubreil do you know a way around this issue?

**Comment by mkruber** [comment]
I think the problem is in `prepare_build` method in `infer/lib/python/inferlib/bucklib.py`. Even though `java-jar-compiler` is set, it adds `javac` to the command. For example, the `cmd` for my infer build is as follows:  

   ```
cmd = [u'<some_path>/infer/infer/lib/python/inferlib/../../../bin/infer', u'--buck', u'--jobs', u'1', u'--java-jar-compiler', u'<some_path>/error_prone_ant*.jar'] + ['--', 'javac'] + sys.argv[1:]
subprocess.check_call(cmd)
```

When I commented out `AbstractJavacSpec.getJavacSource()` in `buck` as follows:

```
   /*    if (getJavacPath().isPresent() && getJavacJarPath().isPresent()) {
      throw new HumanReadableException("Cannot set both javac and javacjar");
    }

    if (getJavacPath().isPresent()) {
      return Javac.Source.EXTERNAL;
    } else */
    if (getJavacJarPath().isPresent()) {
      return Javac.Source.JAR;
    } else {
      return Javac.Source.JDK;
    }
```
then, infer is able to capture the build without any problem. I think fixing `prepare_build` to add `javac` conditionally may resolve this problem.

**Comment by jeremydubreil** [comment]
having the `javac` as part of the command line is fine in theory. It should be used to switch to the Java mode. However, is the code expecting a specific version of `java`? The code here, https://github.com/facebook/infer/blob/8b882ac1dfc49a94b33312d59e4d0badd19272d6/infer/src/integration/Javac.ml#L22, could be related.

What are the benefits of running `infer capture -- buck ...` on Java Buck project over just running `infer -- buck ...`?

**Comment by jvillard** [comment]
> What are the benefits of running `infer capture -- buck ...` on Java Buck project over just running `infer -- buck ...`?

I missed that this is using `infer capture`. Isn't this basically not supported for the Java Buck integration? (in the sense that you can't really run `infer analyze` afterwards and get results) If so infer should warn about this.

**Comment by mkruber** [comment]
@jvillard, To clarify, this problem happens even with `infer -- buck ...` and the patch given above by me is incorrect. It will skip analyzing the build with infer.

**Comment by mkruber** [comment]
@jeremydubreil I am not adding any additional setting to buck and the java version used is 1.8.
