### ISSUE TITLE
test android_hello exception

### ISSUE THREAD

**Issue by shichaowang** [facebook/infer#98]
shichaowang@shichaowang:~/workspace/infer-linux64-v0.1.1/infer/examples/android_hello$ infer -- ./gradlew build
Exception in thread "main" java.lang.RuntimeException: java.net.ConnectException: 连接超时
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
	at org.gradle.wrapper.Install.createDist(Install.java:47)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)

**Comment by sblackshear** [comment]
This looks like it could be a problem with Gradle. Do you see the same problem if you just run `./gradlew build`?
