### ISSUE TITLE
Infer analysis an android project aborted every time.

### ISSUE THREAD

**Issue by StephenYangCN** [facebook/infer#995]
Infer version v0.15.0
JavaPath: /usr/bin/java
Java version "1.8.0_181"
Python 2.7.10

After I execute "infer run -- ./gradlew :app:assembleDebug" for a while, infer always aborted with following err. but I can build success without infer as above assemble command. Thanks for any help.

... ...
cannot find com.mycompany.kit.R$styleable.RecyclerView_fastScrollVerticalThumbDrawable
Skipping because of: Cannot find fieldname

cannot find  com.mycompany.kit.R$styleable.RecyclerView_fastScrollVerticalTrackDrawable
Skipping because of: Cannot find fieldname

Uncaught Internal Error: (Sys_error
  "/Users/cimacpro/.gradle/caches/transforms-1/files-1.1/crashlytics-2.8.0.aar/75fc603595e306264c80c6a60f5b6c00/jars/classes.jar: Too many open files")

Error backtrace:
Raised by primitive operation at file "pervasives.ml", line 389, characters 28-54
Called from file "pervasives.ml" (inlined), line 397, characters 2-47
Called from file "zip.ml", line 221, characters 11-42
Called from file "jFile.ml", line 76, characters 20-35
Called from file "extList.ml", line 154, characters 12-15
Called from file "extList.ml", line 162, characters 2-14
Called from file "java/jClasspath.ml", line 300, characters 44-72
Called from file "java/jMain.ml", line 86, characters 16-57
Called from file "java/jMain.ml" (inlined), line 147, characters 40-79
Called from file "integration/Javac.ml", line 88, characters 48-87
Called from file "infer.ml", line 20, characters 2-36
Called from file "infer.ml", line 130, characters 8-54
... ...
Traceback (most recent call last):
  File "/usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../lib/python/infer.py", line 203, in <module>
    main()
  File "/usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../lib/python/infer.py", line 185, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/usr/local/Cellar/infer/0.15.0/lib/infer/infer/lib/python/inferlib/capture/gradle.py", line 214, in capture
    capture_code = util.run_compilation_commands(cmds)
  File "/usr/local/Cellar/infer/0.15.0/lib/infer/infer/lib/python/inferlib/capture/util.py", line 46, in run_compilation_commands
    if cmd.start() != os.EX_OK:
  File "/usr/local/Cellar/infer/0.15.0/lib/infer/infer/lib/python/inferlib/jwlib.py", line 35, in start
    raise e
... ...

u'@/Users/cimacpro/Documents/coderepo/xproject/infer-out/filelists/gradle_7uFno0.txt']' returned non-zero exit status 2
Internal Error:   /usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../lib/python/infer.py
  -j 16 --project-root
  /Users/cimacpro/Documents/coderepo/xproject --out
  /Users/cimacpro/Documents/coderepo/xproject/infer-out --
  ./gradlew :app: assembleDebug:
  exited with code 1
Error backtrace:
Raised at file "base/Die.ml" (inlined), line 25, characters 6-36
Called from file "base/Logging.ml", line 314, characters 58-80
Called from file "integration/Driver.ml", line 159, characters 2-16
Called from file "integration/Driver.ml", line 280, characters 6-420
Called from file "infer.ml", line 20, characters 2-36
Called from file "infer.ml", line 130, characters 8-54

**Comment by ravarora** [comment]
We are facing the exact same issue.

1. Findbugs is not being run in the build.
2. Ran the following commands
    a. ./gradlew clean then infer run -- ./gradlew assembleDebug
    b. ./gradlew clean then infer run -- ./gradlew assembleRelease
    c. ./gradlew clean then infer run -- ./gradlew build
    All the above commands yield the same error

Internal Error: /usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../lib/python/infer.py
-j 8 --project-root /Users/ravisharora/KCInd/Android/app --out
/Users/ravisharora/KCInd/Android/app/infer-out -- ./gradlew assembleDebug:
exited with code 1
Error backtrace:
Raised at file "base/Die.ml" (inlined), line 25, characters 6-36
Called from file "base/Logging.ml", line 314, characters 58-80
Called from file "integration/Driver.ml", line 159, characters 2-16
Called from file "integration/Driver.ml", line 280, characters 6-420
Called from file "infer.ml", line 20, characters 2-36
Called from file "infer.ml", line 130, characters 8-54

infer-out/logs has the following output
[35572][environment] Analyzer: capture
[35572][environment] Active checkers: annotation reachability (Java), biabduction (C/C++/ObjC, Java), fragment retains view (Java), immutable cast (Java), liveness (C/C++/ObjC), printf args (Java), ownership (C/C++/ObjC), RacerD (C/C++/ObjC, Java), SIOF (C/C++/ObjC), uninitialized variables (C/C++/ObjC)
[35572][ debug] Current working directory: '/Users/ravisharora/KCInd/Android/app'
[35572][ debug] Trying to execute: javac '-J-Duser.language=en' '@/Users/ravisharora/KCInd/Android/app/infer-out/filelists/gradle_T9kqdf.txt' '@/var/folders/fc/hfpr883x57b0mbqdgk87454w0000gn/T/args.tmp.3ff639' 2>'/var/folders/fc/hfpr883x57b0mbqdgk87454w0000gn/T/javac.tmp.ecfa89.out'
[35572][ debug] *** Success. Logs:
[35572][ debug] setting processing env to javac ProcessingEnvironment
Translating 1784 source files (5075 classes)
[35572][environment] Infer log identifier is
[33285][ intern err] /usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../lib/python/infer.py
-j 8 --project-root /Users/ravisharora/KCInd/Android/app --out
/Users/ravisharora/KCInd/Android/app/infer-out -- ./gradlew assembleDebug:
exited with code 1
[33285][ intern err]_

Any help here would be appreciated.
